// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_54_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_ZL14storage_matrix_7_load,
        p_ZL14storage_matrix_15_load,
        p_ZL14storage_matrix_23_load,
        p_ZL14storage_matrix_31_load,
        p_ZL14storage_matrix_39_load,
        p_ZL14storage_matrix_47_load,
        p_ZL14storage_matrix_55_load,
        p_ZL14storage_matrix_63_load,
        p_ZL14storage_matrix_71_load,
        p_ZL14storage_matrix_79_load,
        p_ZL14storage_matrix_87_load,
        p_ZL14storage_matrix_95_load,
        p_ZL14storage_matrix_103_load,
        p_ZL14storage_matrix_111_load,
        p_ZL14storage_matrix_119_load,
        p_ZL14storage_matrix_127_load,
        p_ZL14storage_matrix_135_load,
        p_ZL14storage_matrix_143_load,
        p_ZL14storage_matrix_151_load,
        p_ZL14storage_matrix_159_load,
        p_ZL14storage_matrix_167_load,
        p_ZL14storage_matrix_175_load,
        p_ZL14storage_matrix_183_load,
        p_ZL14storage_matrix_191_load,
        p_ZL14storage_matrix_199_load,
        p_ZL14storage_matrix_207_load,
        p_ZL14storage_matrix_215_load,
        p_ZL14storage_matrix_223_load,
        p_ZL14storage_matrix_231_load,
        p_ZL14storage_matrix_239_load,
        p_ZL14storage_matrix_247_load,
        p_ZL14storage_matrix_255_load,
        p_ZL14storage_matrix_6_load,
        p_ZL14storage_matrix_14_load,
        p_ZL14storage_matrix_22_load,
        p_ZL14storage_matrix_30_load,
        p_ZL14storage_matrix_38_load,
        p_ZL14storage_matrix_46_load,
        p_ZL14storage_matrix_54_load,
        p_ZL14storage_matrix_62_load,
        p_ZL14storage_matrix_70_load,
        p_ZL14storage_matrix_78_load,
        p_ZL14storage_matrix_86_load,
        p_ZL14storage_matrix_94_load,
        p_ZL14storage_matrix_102_load,
        p_ZL14storage_matrix_110_load,
        p_ZL14storage_matrix_118_load,
        p_ZL14storage_matrix_126_load,
        p_ZL14storage_matrix_134_load,
        p_ZL14storage_matrix_142_load,
        p_ZL14storage_matrix_150_load,
        p_ZL14storage_matrix_158_load,
        p_ZL14storage_matrix_166_load,
        p_ZL14storage_matrix_174_load,
        p_ZL14storage_matrix_182_load,
        p_ZL14storage_matrix_190_load,
        p_ZL14storage_matrix_198_load,
        p_ZL14storage_matrix_206_load,
        p_ZL14storage_matrix_214_load,
        p_ZL14storage_matrix_222_load,
        p_ZL14storage_matrix_230_load,
        p_ZL14storage_matrix_238_load,
        p_ZL14storage_matrix_246_load,
        p_ZL14storage_matrix_254_load,
        p_ZL14storage_matrix_5_load,
        p_ZL14storage_matrix_13_load,
        p_ZL14storage_matrix_21_load,
        p_ZL14storage_matrix_29_load,
        p_ZL14storage_matrix_37_load,
        p_ZL14storage_matrix_45_load,
        p_ZL14storage_matrix_53_load,
        p_ZL14storage_matrix_61_load,
        p_ZL14storage_matrix_69_load,
        p_ZL14storage_matrix_77_load,
        p_ZL14storage_matrix_85_load,
        p_ZL14storage_matrix_93_load,
        p_ZL14storage_matrix_101_load,
        p_ZL14storage_matrix_109_load,
        p_ZL14storage_matrix_117_load,
        p_ZL14storage_matrix_125_load,
        p_ZL14storage_matrix_133_load,
        p_ZL14storage_matrix_141_load,
        p_ZL14storage_matrix_149_load,
        p_ZL14storage_matrix_157_load,
        p_ZL14storage_matrix_165_load,
        p_ZL14storage_matrix_173_load,
        p_ZL14storage_matrix_181_load,
        p_ZL14storage_matrix_189_load,
        p_ZL14storage_matrix_197_load,
        p_ZL14storage_matrix_205_load,
        p_ZL14storage_matrix_213_load,
        p_ZL14storage_matrix_221_load,
        p_ZL14storage_matrix_229_load,
        p_ZL14storage_matrix_237_load,
        p_ZL14storage_matrix_245_load,
        p_ZL14storage_matrix_253_load,
        p_ZL14storage_matrix_4_load,
        p_ZL14storage_matrix_12_load,
        p_ZL14storage_matrix_20_load,
        p_ZL14storage_matrix_28_load,
        p_ZL14storage_matrix_36_load,
        p_ZL14storage_matrix_44_load,
        p_ZL14storage_matrix_52_load,
        p_ZL14storage_matrix_60_load,
        p_ZL14storage_matrix_68_load,
        p_ZL14storage_matrix_76_load,
        p_ZL14storage_matrix_84_load,
        p_ZL14storage_matrix_92_load,
        p_ZL14storage_matrix_100_load,
        p_ZL14storage_matrix_108_load,
        p_ZL14storage_matrix_116_load,
        p_ZL14storage_matrix_124_load,
        p_ZL14storage_matrix_132_load,
        p_ZL14storage_matrix_140_load,
        p_ZL14storage_matrix_148_load,
        p_ZL14storage_matrix_156_load,
        p_ZL14storage_matrix_164_load,
        p_ZL14storage_matrix_172_load,
        p_ZL14storage_matrix_180_load,
        p_ZL14storage_matrix_188_load,
        p_ZL14storage_matrix_196_load,
        p_ZL14storage_matrix_204_load,
        p_ZL14storage_matrix_212_load,
        p_ZL14storage_matrix_220_load,
        p_ZL14storage_matrix_228_load,
        p_ZL14storage_matrix_236_load,
        p_ZL14storage_matrix_244_load,
        p_ZL14storage_matrix_252_load,
        p_ZL14storage_matrix_3_load,
        p_ZL14storage_matrix_11_load,
        p_ZL14storage_matrix_19_load,
        p_ZL14storage_matrix_27_load,
        p_ZL14storage_matrix_35_load,
        p_ZL14storage_matrix_43_load,
        p_ZL14storage_matrix_51_load,
        p_ZL14storage_matrix_59_load,
        p_ZL14storage_matrix_67_load,
        p_ZL14storage_matrix_75_load,
        p_ZL14storage_matrix_83_load,
        p_ZL14storage_matrix_91_load,
        p_ZL14storage_matrix_99_load,
        p_ZL14storage_matrix_107_load,
        p_ZL14storage_matrix_115_load,
        p_ZL14storage_matrix_123_load,
        p_ZL14storage_matrix_131_load,
        p_ZL14storage_matrix_139_load,
        p_ZL14storage_matrix_147_load,
        p_ZL14storage_matrix_155_load,
        p_ZL14storage_matrix_163_load,
        p_ZL14storage_matrix_171_load,
        p_ZL14storage_matrix_179_load,
        p_ZL14storage_matrix_187_load,
        p_ZL14storage_matrix_195_load,
        p_ZL14storage_matrix_203_load,
        p_ZL14storage_matrix_211_load,
        p_ZL14storage_matrix_219_load,
        p_ZL14storage_matrix_227_load,
        p_ZL14storage_matrix_235_load,
        p_ZL14storage_matrix_243_load,
        p_ZL14storage_matrix_251_load,
        p_ZL14storage_matrix_2_load,
        p_ZL14storage_matrix_10_load,
        p_ZL14storage_matrix_18_load,
        p_ZL14storage_matrix_26_load,
        p_ZL14storage_matrix_34_load,
        p_ZL14storage_matrix_42_load,
        p_ZL14storage_matrix_50_load,
        p_ZL14storage_matrix_58_load,
        p_ZL14storage_matrix_66_load,
        p_ZL14storage_matrix_74_load,
        p_ZL14storage_matrix_82_load,
        p_ZL14storage_matrix_90_load,
        p_ZL14storage_matrix_98_load,
        p_ZL14storage_matrix_106_load,
        p_ZL14storage_matrix_114_load,
        p_ZL14storage_matrix_122_load,
        p_ZL14storage_matrix_130_load,
        p_ZL14storage_matrix_138_load,
        p_ZL14storage_matrix_146_load,
        p_ZL14storage_matrix_154_load,
        p_ZL14storage_matrix_162_load,
        p_ZL14storage_matrix_170_load,
        p_ZL14storage_matrix_178_load,
        p_ZL14storage_matrix_186_load,
        p_ZL14storage_matrix_194_load,
        p_ZL14storage_matrix_202_load,
        p_ZL14storage_matrix_210_load,
        p_ZL14storage_matrix_218_load,
        p_ZL14storage_matrix_226_load,
        p_ZL14storage_matrix_234_load,
        p_ZL14storage_matrix_242_load,
        p_ZL14storage_matrix_250_load,
        p_ZL14storage_matrix_1_load,
        p_ZL14storage_matrix_9_load,
        p_ZL14storage_matrix_17_load,
        p_ZL14storage_matrix_25_load,
        p_ZL14storage_matrix_33_load,
        p_ZL14storage_matrix_41_load,
        p_ZL14storage_matrix_49_load,
        p_ZL14storage_matrix_57_load,
        p_ZL14storage_matrix_65_load,
        p_ZL14storage_matrix_73_load,
        p_ZL14storage_matrix_81_load,
        p_ZL14storage_matrix_89_load,
        p_ZL14storage_matrix_97_load,
        p_ZL14storage_matrix_105_load,
        p_ZL14storage_matrix_113_load,
        p_ZL14storage_matrix_121_load,
        p_ZL14storage_matrix_129_load,
        p_ZL14storage_matrix_137_load,
        p_ZL14storage_matrix_145_load,
        p_ZL14storage_matrix_153_load,
        p_ZL14storage_matrix_161_load,
        p_ZL14storage_matrix_169_load,
        p_ZL14storage_matrix_177_load,
        p_ZL14storage_matrix_185_load,
        p_ZL14storage_matrix_193_load,
        p_ZL14storage_matrix_201_load,
        p_ZL14storage_matrix_209_load,
        p_ZL14storage_matrix_217_load,
        p_ZL14storage_matrix_225_load,
        p_ZL14storage_matrix_233_load,
        p_ZL14storage_matrix_241_load,
        p_ZL14storage_matrix_249_load,
        v_V_7_address0,
        v_V_7_ce0,
        v_V_7_we0,
        v_V_7_d0,
        v_V_7_address1,
        v_V_7_ce1,
        v_V_7_q1,
        v_V_6_address0,
        v_V_6_ce0,
        v_V_6_we0,
        v_V_6_d0,
        v_V_6_address1,
        v_V_6_ce1,
        v_V_6_q1,
        v_V_5_address0,
        v_V_5_ce0,
        v_V_5_we0,
        v_V_5_d0,
        v_V_5_address1,
        v_V_5_ce1,
        v_V_5_q1,
        v_V_4_address0,
        v_V_4_ce0,
        v_V_4_we0,
        v_V_4_d0,
        v_V_4_address1,
        v_V_4_ce1,
        v_V_4_q1,
        v_V_3_address0,
        v_V_3_ce0,
        v_V_3_we0,
        v_V_3_d0,
        v_V_3_address1,
        v_V_3_ce1,
        v_V_3_q1,
        v_V_2_address0,
        v_V_2_ce0,
        v_V_2_we0,
        v_V_2_d0,
        v_V_2_address1,
        v_V_2_ce1,
        v_V_2_q1,
        v_V_1_address0,
        v_V_1_ce0,
        v_V_1_we0,
        v_V_1_d0,
        v_V_1_address1,
        v_V_1_ce1,
        v_V_1_q1,
        v_V_address0,
        v_V_ce0,
        v_V_we0,
        v_V_d0,
        v_V_address1,
        v_V_ce1,
        v_V_q1,
        p_ZL14storage_matrix_0_load,
        p_ZL14storage_matrix_8_load,
        p_ZL14storage_matrix_16_load,
        p_ZL14storage_matrix_24_load,
        p_ZL14storage_matrix_32_load,
        p_ZL14storage_matrix_40_load,
        p_ZL14storage_matrix_48_load,
        p_ZL14storage_matrix_56_load,
        p_ZL14storage_matrix_64_load,
        p_ZL14storage_matrix_72_load,
        p_ZL14storage_matrix_80_load,
        p_ZL14storage_matrix_88_load,
        p_ZL14storage_matrix_96_load,
        p_ZL14storage_matrix_104_load,
        p_ZL14storage_matrix_112_load,
        p_ZL14storage_matrix_120_load,
        p_ZL14storage_matrix_128_load,
        p_ZL14storage_matrix_136_load,
        p_ZL14storage_matrix_144_load,
        p_ZL14storage_matrix_152_load,
        p_ZL14storage_matrix_160_load,
        p_ZL14storage_matrix_168_load,
        p_ZL14storage_matrix_176_load,
        p_ZL14storage_matrix_184_load,
        p_ZL14storage_matrix_192_load,
        p_ZL14storage_matrix_200_load,
        p_ZL14storage_matrix_208_load,
        p_ZL14storage_matrix_216_load,
        p_ZL14storage_matrix_224_load,
        p_ZL14storage_matrix_232_load,
        p_ZL14storage_matrix_240_load,
        p_ZL14storage_matrix_248_load,
        ref_timer_V_address0,
        ref_timer_V_ce0,
        ref_timer_V_q0,
        ref_timer_V_1_address0,
        ref_timer_V_1_ce0,
        ref_timer_V_1_q0,
        ref_timer_V_2_address0,
        ref_timer_V_2_ce0,
        ref_timer_V_2_q0,
        ref_timer_V_3_address0,
        ref_timer_V_3_ce0,
        ref_timer_V_3_q0,
        ref_timer_V_4_address0,
        ref_timer_V_4_ce0,
        ref_timer_V_4_q0,
        ref_timer_V_5_address0,
        ref_timer_V_5_ce0,
        ref_timer_V_5_q0,
        ref_timer_V_6_address0,
        ref_timer_V_6_ce0,
        ref_timer_V_6_q0,
        ref_timer_V_7_address0,
        ref_timer_V_7_ce0,
        ref_timer_V_7_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] p_ZL14storage_matrix_7_load;
input  [0:0] p_ZL14storage_matrix_15_load;
input  [0:0] p_ZL14storage_matrix_23_load;
input  [0:0] p_ZL14storage_matrix_31_load;
input  [0:0] p_ZL14storage_matrix_39_load;
input  [0:0] p_ZL14storage_matrix_47_load;
input  [0:0] p_ZL14storage_matrix_55_load;
input  [0:0] p_ZL14storage_matrix_63_load;
input  [0:0] p_ZL14storage_matrix_71_load;
input  [0:0] p_ZL14storage_matrix_79_load;
input  [0:0] p_ZL14storage_matrix_87_load;
input  [0:0] p_ZL14storage_matrix_95_load;
input  [0:0] p_ZL14storage_matrix_103_load;
input  [0:0] p_ZL14storage_matrix_111_load;
input  [0:0] p_ZL14storage_matrix_119_load;
input  [0:0] p_ZL14storage_matrix_127_load;
input  [0:0] p_ZL14storage_matrix_135_load;
input  [0:0] p_ZL14storage_matrix_143_load;
input  [0:0] p_ZL14storage_matrix_151_load;
input  [0:0] p_ZL14storage_matrix_159_load;
input  [0:0] p_ZL14storage_matrix_167_load;
input  [0:0] p_ZL14storage_matrix_175_load;
input  [0:0] p_ZL14storage_matrix_183_load;
input  [0:0] p_ZL14storage_matrix_191_load;
input  [0:0] p_ZL14storage_matrix_199_load;
input  [0:0] p_ZL14storage_matrix_207_load;
input  [0:0] p_ZL14storage_matrix_215_load;
input  [0:0] p_ZL14storage_matrix_223_load;
input  [0:0] p_ZL14storage_matrix_231_load;
input  [0:0] p_ZL14storage_matrix_239_load;
input  [0:0] p_ZL14storage_matrix_247_load;
input  [0:0] p_ZL14storage_matrix_255_load;
input  [0:0] p_ZL14storage_matrix_6_load;
input  [0:0] p_ZL14storage_matrix_14_load;
input  [0:0] p_ZL14storage_matrix_22_load;
input  [0:0] p_ZL14storage_matrix_30_load;
input  [0:0] p_ZL14storage_matrix_38_load;
input  [0:0] p_ZL14storage_matrix_46_load;
input  [0:0] p_ZL14storage_matrix_54_load;
input  [0:0] p_ZL14storage_matrix_62_load;
input  [0:0] p_ZL14storage_matrix_70_load;
input  [0:0] p_ZL14storage_matrix_78_load;
input  [0:0] p_ZL14storage_matrix_86_load;
input  [0:0] p_ZL14storage_matrix_94_load;
input  [0:0] p_ZL14storage_matrix_102_load;
input  [0:0] p_ZL14storage_matrix_110_load;
input  [0:0] p_ZL14storage_matrix_118_load;
input  [0:0] p_ZL14storage_matrix_126_load;
input  [0:0] p_ZL14storage_matrix_134_load;
input  [0:0] p_ZL14storage_matrix_142_load;
input  [0:0] p_ZL14storage_matrix_150_load;
input  [0:0] p_ZL14storage_matrix_158_load;
input  [0:0] p_ZL14storage_matrix_166_load;
input  [0:0] p_ZL14storage_matrix_174_load;
input  [0:0] p_ZL14storage_matrix_182_load;
input  [0:0] p_ZL14storage_matrix_190_load;
input  [0:0] p_ZL14storage_matrix_198_load;
input  [0:0] p_ZL14storage_matrix_206_load;
input  [0:0] p_ZL14storage_matrix_214_load;
input  [0:0] p_ZL14storage_matrix_222_load;
input  [0:0] p_ZL14storage_matrix_230_load;
input  [0:0] p_ZL14storage_matrix_238_load;
input  [0:0] p_ZL14storage_matrix_246_load;
input  [0:0] p_ZL14storage_matrix_254_load;
input  [0:0] p_ZL14storage_matrix_5_load;
input  [0:0] p_ZL14storage_matrix_13_load;
input  [0:0] p_ZL14storage_matrix_21_load;
input  [0:0] p_ZL14storage_matrix_29_load;
input  [0:0] p_ZL14storage_matrix_37_load;
input  [0:0] p_ZL14storage_matrix_45_load;
input  [0:0] p_ZL14storage_matrix_53_load;
input  [0:0] p_ZL14storage_matrix_61_load;
input  [0:0] p_ZL14storage_matrix_69_load;
input  [0:0] p_ZL14storage_matrix_77_load;
input  [0:0] p_ZL14storage_matrix_85_load;
input  [0:0] p_ZL14storage_matrix_93_load;
input  [0:0] p_ZL14storage_matrix_101_load;
input  [0:0] p_ZL14storage_matrix_109_load;
input  [0:0] p_ZL14storage_matrix_117_load;
input  [0:0] p_ZL14storage_matrix_125_load;
input  [0:0] p_ZL14storage_matrix_133_load;
input  [0:0] p_ZL14storage_matrix_141_load;
input  [0:0] p_ZL14storage_matrix_149_load;
input  [0:0] p_ZL14storage_matrix_157_load;
input  [0:0] p_ZL14storage_matrix_165_load;
input  [0:0] p_ZL14storage_matrix_173_load;
input  [0:0] p_ZL14storage_matrix_181_load;
input  [0:0] p_ZL14storage_matrix_189_load;
input  [0:0] p_ZL14storage_matrix_197_load;
input  [0:0] p_ZL14storage_matrix_205_load;
input  [0:0] p_ZL14storage_matrix_213_load;
input  [0:0] p_ZL14storage_matrix_221_load;
input  [0:0] p_ZL14storage_matrix_229_load;
input  [0:0] p_ZL14storage_matrix_237_load;
input  [0:0] p_ZL14storage_matrix_245_load;
input  [0:0] p_ZL14storage_matrix_253_load;
input  [0:0] p_ZL14storage_matrix_4_load;
input  [0:0] p_ZL14storage_matrix_12_load;
input  [0:0] p_ZL14storage_matrix_20_load;
input  [0:0] p_ZL14storage_matrix_28_load;
input  [0:0] p_ZL14storage_matrix_36_load;
input  [0:0] p_ZL14storage_matrix_44_load;
input  [0:0] p_ZL14storage_matrix_52_load;
input  [0:0] p_ZL14storage_matrix_60_load;
input  [0:0] p_ZL14storage_matrix_68_load;
input  [0:0] p_ZL14storage_matrix_76_load;
input  [0:0] p_ZL14storage_matrix_84_load;
input  [0:0] p_ZL14storage_matrix_92_load;
input  [0:0] p_ZL14storage_matrix_100_load;
input  [0:0] p_ZL14storage_matrix_108_load;
input  [0:0] p_ZL14storage_matrix_116_load;
input  [0:0] p_ZL14storage_matrix_124_load;
input  [0:0] p_ZL14storage_matrix_132_load;
input  [0:0] p_ZL14storage_matrix_140_load;
input  [0:0] p_ZL14storage_matrix_148_load;
input  [0:0] p_ZL14storage_matrix_156_load;
input  [0:0] p_ZL14storage_matrix_164_load;
input  [0:0] p_ZL14storage_matrix_172_load;
input  [0:0] p_ZL14storage_matrix_180_load;
input  [0:0] p_ZL14storage_matrix_188_load;
input  [0:0] p_ZL14storage_matrix_196_load;
input  [0:0] p_ZL14storage_matrix_204_load;
input  [0:0] p_ZL14storage_matrix_212_load;
input  [0:0] p_ZL14storage_matrix_220_load;
input  [0:0] p_ZL14storage_matrix_228_load;
input  [0:0] p_ZL14storage_matrix_236_load;
input  [0:0] p_ZL14storage_matrix_244_load;
input  [0:0] p_ZL14storage_matrix_252_load;
input  [0:0] p_ZL14storage_matrix_3_load;
input  [0:0] p_ZL14storage_matrix_11_load;
input  [0:0] p_ZL14storage_matrix_19_load;
input  [0:0] p_ZL14storage_matrix_27_load;
input  [0:0] p_ZL14storage_matrix_35_load;
input  [0:0] p_ZL14storage_matrix_43_load;
input  [0:0] p_ZL14storage_matrix_51_load;
input  [0:0] p_ZL14storage_matrix_59_load;
input  [0:0] p_ZL14storage_matrix_67_load;
input  [0:0] p_ZL14storage_matrix_75_load;
input  [0:0] p_ZL14storage_matrix_83_load;
input  [0:0] p_ZL14storage_matrix_91_load;
input  [0:0] p_ZL14storage_matrix_99_load;
input  [0:0] p_ZL14storage_matrix_107_load;
input  [0:0] p_ZL14storage_matrix_115_load;
input  [0:0] p_ZL14storage_matrix_123_load;
input  [0:0] p_ZL14storage_matrix_131_load;
input  [0:0] p_ZL14storage_matrix_139_load;
input  [0:0] p_ZL14storage_matrix_147_load;
input  [0:0] p_ZL14storage_matrix_155_load;
input  [0:0] p_ZL14storage_matrix_163_load;
input  [0:0] p_ZL14storage_matrix_171_load;
input  [0:0] p_ZL14storage_matrix_179_load;
input  [0:0] p_ZL14storage_matrix_187_load;
input  [0:0] p_ZL14storage_matrix_195_load;
input  [0:0] p_ZL14storage_matrix_203_load;
input  [0:0] p_ZL14storage_matrix_211_load;
input  [0:0] p_ZL14storage_matrix_219_load;
input  [0:0] p_ZL14storage_matrix_227_load;
input  [0:0] p_ZL14storage_matrix_235_load;
input  [0:0] p_ZL14storage_matrix_243_load;
input  [0:0] p_ZL14storage_matrix_251_load;
input  [0:0] p_ZL14storage_matrix_2_load;
input  [0:0] p_ZL14storage_matrix_10_load;
input  [0:0] p_ZL14storage_matrix_18_load;
input  [0:0] p_ZL14storage_matrix_26_load;
input  [0:0] p_ZL14storage_matrix_34_load;
input  [0:0] p_ZL14storage_matrix_42_load;
input  [0:0] p_ZL14storage_matrix_50_load;
input  [0:0] p_ZL14storage_matrix_58_load;
input  [0:0] p_ZL14storage_matrix_66_load;
input  [0:0] p_ZL14storage_matrix_74_load;
input  [0:0] p_ZL14storage_matrix_82_load;
input  [0:0] p_ZL14storage_matrix_90_load;
input  [0:0] p_ZL14storage_matrix_98_load;
input  [0:0] p_ZL14storage_matrix_106_load;
input  [0:0] p_ZL14storage_matrix_114_load;
input  [0:0] p_ZL14storage_matrix_122_load;
input  [0:0] p_ZL14storage_matrix_130_load;
input  [0:0] p_ZL14storage_matrix_138_load;
input  [0:0] p_ZL14storage_matrix_146_load;
input  [0:0] p_ZL14storage_matrix_154_load;
input  [0:0] p_ZL14storage_matrix_162_load;
input  [0:0] p_ZL14storage_matrix_170_load;
input  [0:0] p_ZL14storage_matrix_178_load;
input  [0:0] p_ZL14storage_matrix_186_load;
input  [0:0] p_ZL14storage_matrix_194_load;
input  [0:0] p_ZL14storage_matrix_202_load;
input  [0:0] p_ZL14storage_matrix_210_load;
input  [0:0] p_ZL14storage_matrix_218_load;
input  [0:0] p_ZL14storage_matrix_226_load;
input  [0:0] p_ZL14storage_matrix_234_load;
input  [0:0] p_ZL14storage_matrix_242_load;
input  [0:0] p_ZL14storage_matrix_250_load;
input  [0:0] p_ZL14storage_matrix_1_load;
input  [0:0] p_ZL14storage_matrix_9_load;
input  [0:0] p_ZL14storage_matrix_17_load;
input  [0:0] p_ZL14storage_matrix_25_load;
input  [0:0] p_ZL14storage_matrix_33_load;
input  [0:0] p_ZL14storage_matrix_41_load;
input  [0:0] p_ZL14storage_matrix_49_load;
input  [0:0] p_ZL14storage_matrix_57_load;
input  [0:0] p_ZL14storage_matrix_65_load;
input  [0:0] p_ZL14storage_matrix_73_load;
input  [0:0] p_ZL14storage_matrix_81_load;
input  [0:0] p_ZL14storage_matrix_89_load;
input  [0:0] p_ZL14storage_matrix_97_load;
input  [0:0] p_ZL14storage_matrix_105_load;
input  [0:0] p_ZL14storage_matrix_113_load;
input  [0:0] p_ZL14storage_matrix_121_load;
input  [0:0] p_ZL14storage_matrix_129_load;
input  [0:0] p_ZL14storage_matrix_137_load;
input  [0:0] p_ZL14storage_matrix_145_load;
input  [0:0] p_ZL14storage_matrix_153_load;
input  [0:0] p_ZL14storage_matrix_161_load;
input  [0:0] p_ZL14storage_matrix_169_load;
input  [0:0] p_ZL14storage_matrix_177_load;
input  [0:0] p_ZL14storage_matrix_185_load;
input  [0:0] p_ZL14storage_matrix_193_load;
input  [0:0] p_ZL14storage_matrix_201_load;
input  [0:0] p_ZL14storage_matrix_209_load;
input  [0:0] p_ZL14storage_matrix_217_load;
input  [0:0] p_ZL14storage_matrix_225_load;
input  [0:0] p_ZL14storage_matrix_233_load;
input  [0:0] p_ZL14storage_matrix_241_load;
input  [0:0] p_ZL14storage_matrix_249_load;
output  [4:0] v_V_7_address0;
output   v_V_7_ce0;
output   v_V_7_we0;
output  [6:0] v_V_7_d0;
output  [4:0] v_V_7_address1;
output   v_V_7_ce1;
input  [6:0] v_V_7_q1;
output  [4:0] v_V_6_address0;
output   v_V_6_ce0;
output   v_V_6_we0;
output  [6:0] v_V_6_d0;
output  [4:0] v_V_6_address1;
output   v_V_6_ce1;
input  [6:0] v_V_6_q1;
output  [4:0] v_V_5_address0;
output   v_V_5_ce0;
output   v_V_5_we0;
output  [6:0] v_V_5_d0;
output  [4:0] v_V_5_address1;
output   v_V_5_ce1;
input  [6:0] v_V_5_q1;
output  [4:0] v_V_4_address0;
output   v_V_4_ce0;
output   v_V_4_we0;
output  [6:0] v_V_4_d0;
output  [4:0] v_V_4_address1;
output   v_V_4_ce1;
input  [6:0] v_V_4_q1;
output  [4:0] v_V_3_address0;
output   v_V_3_ce0;
output   v_V_3_we0;
output  [6:0] v_V_3_d0;
output  [4:0] v_V_3_address1;
output   v_V_3_ce1;
input  [6:0] v_V_3_q1;
output  [4:0] v_V_2_address0;
output   v_V_2_ce0;
output   v_V_2_we0;
output  [6:0] v_V_2_d0;
output  [4:0] v_V_2_address1;
output   v_V_2_ce1;
input  [6:0] v_V_2_q1;
output  [4:0] v_V_1_address0;
output   v_V_1_ce0;
output   v_V_1_we0;
output  [6:0] v_V_1_d0;
output  [4:0] v_V_1_address1;
output   v_V_1_ce1;
input  [6:0] v_V_1_q1;
output  [4:0] v_V_address0;
output   v_V_ce0;
output   v_V_we0;
output  [6:0] v_V_d0;
output  [4:0] v_V_address1;
output   v_V_ce1;
input  [6:0] v_V_q1;
input  [0:0] p_ZL14storage_matrix_0_load;
input  [0:0] p_ZL14storage_matrix_8_load;
input  [0:0] p_ZL14storage_matrix_16_load;
input  [0:0] p_ZL14storage_matrix_24_load;
input  [0:0] p_ZL14storage_matrix_32_load;
input  [0:0] p_ZL14storage_matrix_40_load;
input  [0:0] p_ZL14storage_matrix_48_load;
input  [0:0] p_ZL14storage_matrix_56_load;
input  [0:0] p_ZL14storage_matrix_64_load;
input  [0:0] p_ZL14storage_matrix_72_load;
input  [0:0] p_ZL14storage_matrix_80_load;
input  [0:0] p_ZL14storage_matrix_88_load;
input  [0:0] p_ZL14storage_matrix_96_load;
input  [0:0] p_ZL14storage_matrix_104_load;
input  [0:0] p_ZL14storage_matrix_112_load;
input  [0:0] p_ZL14storage_matrix_120_load;
input  [0:0] p_ZL14storage_matrix_128_load;
input  [0:0] p_ZL14storage_matrix_136_load;
input  [0:0] p_ZL14storage_matrix_144_load;
input  [0:0] p_ZL14storage_matrix_152_load;
input  [0:0] p_ZL14storage_matrix_160_load;
input  [0:0] p_ZL14storage_matrix_168_load;
input  [0:0] p_ZL14storage_matrix_176_load;
input  [0:0] p_ZL14storage_matrix_184_load;
input  [0:0] p_ZL14storage_matrix_192_load;
input  [0:0] p_ZL14storage_matrix_200_load;
input  [0:0] p_ZL14storage_matrix_208_load;
input  [0:0] p_ZL14storage_matrix_216_load;
input  [0:0] p_ZL14storage_matrix_224_load;
input  [0:0] p_ZL14storage_matrix_232_load;
input  [0:0] p_ZL14storage_matrix_240_load;
input  [0:0] p_ZL14storage_matrix_248_load;
output  [4:0] ref_timer_V_address0;
output   ref_timer_V_ce0;
input  [2:0] ref_timer_V_q0;
output  [4:0] ref_timer_V_1_address0;
output   ref_timer_V_1_ce0;
input  [2:0] ref_timer_V_1_q0;
output  [4:0] ref_timer_V_2_address0;
output   ref_timer_V_2_ce0;
input  [2:0] ref_timer_V_2_q0;
output  [4:0] ref_timer_V_3_address0;
output   ref_timer_V_3_ce0;
input  [2:0] ref_timer_V_3_q0;
output  [4:0] ref_timer_V_4_address0;
output   ref_timer_V_4_ce0;
input  [2:0] ref_timer_V_4_q0;
output  [4:0] ref_timer_V_5_address0;
output   ref_timer_V_5_ce0;
input  [2:0] ref_timer_V_5_q0;
output  [4:0] ref_timer_V_6_address0;
output   ref_timer_V_6_ce0;
input  [2:0] ref_timer_V_6_q0;
output  [4:0] ref_timer_V_7_address0;
output   ref_timer_V_7_ce0;
input  [2:0] ref_timer_V_7_q0;

reg ap_idle;
reg v_V_7_ce0;
reg v_V_7_we0;
reg v_V_7_ce1;
reg v_V_6_ce0;
reg v_V_6_we0;
reg v_V_6_ce1;
reg v_V_5_ce0;
reg v_V_5_we0;
reg v_V_5_ce1;
reg v_V_4_ce0;
reg v_V_4_we0;
reg v_V_4_ce1;
reg v_V_3_ce0;
reg v_V_3_we0;
reg v_V_3_ce1;
reg v_V_2_ce0;
reg v_V_2_we0;
reg v_V_2_ce1;
reg v_V_1_ce0;
reg v_V_1_we0;
reg v_V_1_ce1;
reg v_V_ce0;
reg v_V_we0;
reg v_V_ce1;
reg ref_timer_V_ce0;
reg ref_timer_V_1_ce0;
reg ref_timer_V_2_ce0;
reg ref_timer_V_3_ce0;
reg ref_timer_V_4_ce0;
reg ref_timer_V_5_ce0;
reg ref_timer_V_6_ce0;
reg ref_timer_V_7_ce0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln54_fu_2364_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln54_fu_2376_p1;
reg   [63:0] zext_ln54_reg_3072;
wire   [0:0] tmp_fu_2392_p34;
reg   [0:0] tmp_reg_3084;
reg   [0:0] tmp_reg_3084_pp0_iter1_reg;
wire   [0:0] tmp_1_fu_2462_p34;
reg   [0:0] tmp_1_reg_3093;
reg   [0:0] tmp_1_reg_3093_pp0_iter1_reg;
wire   [0:0] tmp_3_fu_2532_p34;
reg   [0:0] tmp_3_reg_3102;
reg   [0:0] tmp_3_reg_3102_pp0_iter1_reg;
wire   [0:0] tmp_4_fu_2602_p34;
reg   [0:0] tmp_4_reg_3111;
reg   [0:0] tmp_4_reg_3111_pp0_iter1_reg;
wire   [0:0] tmp_5_fu_2672_p34;
reg   [0:0] tmp_5_reg_3120;
reg   [0:0] tmp_5_reg_3120_pp0_iter1_reg;
wire   [0:0] tmp_7_fu_2742_p34;
reg   [0:0] tmp_7_reg_3129;
reg   [0:0] tmp_7_reg_3129_pp0_iter1_reg;
wire   [0:0] tmp_8_fu_2812_p34;
reg   [0:0] tmp_8_reg_3138;
reg   [0:0] tmp_8_reg_3138_pp0_iter1_reg;
wire   [0:0] tmp_9_fu_2882_p34;
reg   [0:0] tmp_9_reg_3147;
reg   [0:0] tmp_9_reg_3147_pp0_iter1_reg;
wire   [0:0] icmp_ln1019_fu_2957_p2;
reg   [0:0] icmp_ln1019_reg_3156;
reg   [4:0] v_V_addr_reg_3160;
wire   [0:0] icmp_ln1019_1_fu_2963_p2;
reg   [0:0] icmp_ln1019_1_reg_3166;
reg   [4:0] v_V_1_addr_reg_3170;
wire   [0:0] icmp_ln1019_2_fu_2969_p2;
reg   [0:0] icmp_ln1019_2_reg_3176;
reg   [4:0] v_V_2_addr_reg_3180;
wire   [0:0] icmp_ln1019_3_fu_2975_p2;
reg   [0:0] icmp_ln1019_3_reg_3186;
reg   [4:0] v_V_3_addr_reg_3190;
wire   [0:0] icmp_ln1019_4_fu_2981_p2;
reg   [0:0] icmp_ln1019_4_reg_3196;
reg   [4:0] v_V_4_addr_reg_3200;
wire   [0:0] icmp_ln1019_5_fu_2987_p2;
reg   [0:0] icmp_ln1019_5_reg_3206;
reg   [4:0] v_V_5_addr_reg_3210;
wire   [0:0] icmp_ln1019_6_fu_2993_p2;
reg   [0:0] icmp_ln1019_6_reg_3216;
reg   [4:0] v_V_6_addr_reg_3220;
wire   [0:0] icmp_ln1019_7_fu_2999_p2;
reg   [0:0] icmp_ln1019_7_reg_3226;
reg   [4:0] v_V_7_addr_reg_3230;
wire    ap_block_pp0_stage0;
reg   [5:0] bank_fu_576;
wire   [5:0] add_ln54_fu_2370_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_bank_1;
wire   [4:0] trunc_ln58_fu_2388_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

spiking_binam_mux_325_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 1 ),
    .din17_WIDTH( 1 ),
    .din18_WIDTH( 1 ),
    .din19_WIDTH( 1 ),
    .din20_WIDTH( 1 ),
    .din21_WIDTH( 1 ),
    .din22_WIDTH( 1 ),
    .din23_WIDTH( 1 ),
    .din24_WIDTH( 1 ),
    .din25_WIDTH( 1 ),
    .din26_WIDTH( 1 ),
    .din27_WIDTH( 1 ),
    .din28_WIDTH( 1 ),
    .din29_WIDTH( 1 ),
    .din30_WIDTH( 1 ),
    .din31_WIDTH( 1 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 1 ))
mux_325_1_1_1_U17(
    .din0(p_ZL14storage_matrix_0_load),
    .din1(p_ZL14storage_matrix_8_load),
    .din2(p_ZL14storage_matrix_16_load),
    .din3(p_ZL14storage_matrix_24_load),
    .din4(p_ZL14storage_matrix_32_load),
    .din5(p_ZL14storage_matrix_40_load),
    .din6(p_ZL14storage_matrix_48_load),
    .din7(p_ZL14storage_matrix_56_load),
    .din8(p_ZL14storage_matrix_64_load),
    .din9(p_ZL14storage_matrix_72_load),
    .din10(p_ZL14storage_matrix_80_load),
    .din11(p_ZL14storage_matrix_88_load),
    .din12(p_ZL14storage_matrix_96_load),
    .din13(p_ZL14storage_matrix_104_load),
    .din14(p_ZL14storage_matrix_112_load),
    .din15(p_ZL14storage_matrix_120_load),
    .din16(p_ZL14storage_matrix_128_load),
    .din17(p_ZL14storage_matrix_136_load),
    .din18(p_ZL14storage_matrix_144_load),
    .din19(p_ZL14storage_matrix_152_load),
    .din20(p_ZL14storage_matrix_160_load),
    .din21(p_ZL14storage_matrix_168_load),
    .din22(p_ZL14storage_matrix_176_load),
    .din23(p_ZL14storage_matrix_184_load),
    .din24(p_ZL14storage_matrix_192_load),
    .din25(p_ZL14storage_matrix_200_load),
    .din26(p_ZL14storage_matrix_208_load),
    .din27(p_ZL14storage_matrix_216_load),
    .din28(p_ZL14storage_matrix_224_load),
    .din29(p_ZL14storage_matrix_232_load),
    .din30(p_ZL14storage_matrix_240_load),
    .din31(p_ZL14storage_matrix_248_load),
    .din32(trunc_ln58_fu_2388_p1),
    .dout(tmp_fu_2392_p34)
);

spiking_binam_mux_325_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 1 ),
    .din17_WIDTH( 1 ),
    .din18_WIDTH( 1 ),
    .din19_WIDTH( 1 ),
    .din20_WIDTH( 1 ),
    .din21_WIDTH( 1 ),
    .din22_WIDTH( 1 ),
    .din23_WIDTH( 1 ),
    .din24_WIDTH( 1 ),
    .din25_WIDTH( 1 ),
    .din26_WIDTH( 1 ),
    .din27_WIDTH( 1 ),
    .din28_WIDTH( 1 ),
    .din29_WIDTH( 1 ),
    .din30_WIDTH( 1 ),
    .din31_WIDTH( 1 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 1 ))
mux_325_1_1_1_U18(
    .din0(p_ZL14storage_matrix_1_load),
    .din1(p_ZL14storage_matrix_9_load),
    .din2(p_ZL14storage_matrix_17_load),
    .din3(p_ZL14storage_matrix_25_load),
    .din4(p_ZL14storage_matrix_33_load),
    .din5(p_ZL14storage_matrix_41_load),
    .din6(p_ZL14storage_matrix_49_load),
    .din7(p_ZL14storage_matrix_57_load),
    .din8(p_ZL14storage_matrix_65_load),
    .din9(p_ZL14storage_matrix_73_load),
    .din10(p_ZL14storage_matrix_81_load),
    .din11(p_ZL14storage_matrix_89_load),
    .din12(p_ZL14storage_matrix_97_load),
    .din13(p_ZL14storage_matrix_105_load),
    .din14(p_ZL14storage_matrix_113_load),
    .din15(p_ZL14storage_matrix_121_load),
    .din16(p_ZL14storage_matrix_129_load),
    .din17(p_ZL14storage_matrix_137_load),
    .din18(p_ZL14storage_matrix_145_load),
    .din19(p_ZL14storage_matrix_153_load),
    .din20(p_ZL14storage_matrix_161_load),
    .din21(p_ZL14storage_matrix_169_load),
    .din22(p_ZL14storage_matrix_177_load),
    .din23(p_ZL14storage_matrix_185_load),
    .din24(p_ZL14storage_matrix_193_load),
    .din25(p_ZL14storage_matrix_201_load),
    .din26(p_ZL14storage_matrix_209_load),
    .din27(p_ZL14storage_matrix_217_load),
    .din28(p_ZL14storage_matrix_225_load),
    .din29(p_ZL14storage_matrix_233_load),
    .din30(p_ZL14storage_matrix_241_load),
    .din31(p_ZL14storage_matrix_249_load),
    .din32(trunc_ln58_fu_2388_p1),
    .dout(tmp_1_fu_2462_p34)
);

spiking_binam_mux_325_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 1 ),
    .din17_WIDTH( 1 ),
    .din18_WIDTH( 1 ),
    .din19_WIDTH( 1 ),
    .din20_WIDTH( 1 ),
    .din21_WIDTH( 1 ),
    .din22_WIDTH( 1 ),
    .din23_WIDTH( 1 ),
    .din24_WIDTH( 1 ),
    .din25_WIDTH( 1 ),
    .din26_WIDTH( 1 ),
    .din27_WIDTH( 1 ),
    .din28_WIDTH( 1 ),
    .din29_WIDTH( 1 ),
    .din30_WIDTH( 1 ),
    .din31_WIDTH( 1 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 1 ))
mux_325_1_1_1_U19(
    .din0(p_ZL14storage_matrix_2_load),
    .din1(p_ZL14storage_matrix_10_load),
    .din2(p_ZL14storage_matrix_18_load),
    .din3(p_ZL14storage_matrix_26_load),
    .din4(p_ZL14storage_matrix_34_load),
    .din5(p_ZL14storage_matrix_42_load),
    .din6(p_ZL14storage_matrix_50_load),
    .din7(p_ZL14storage_matrix_58_load),
    .din8(p_ZL14storage_matrix_66_load),
    .din9(p_ZL14storage_matrix_74_load),
    .din10(p_ZL14storage_matrix_82_load),
    .din11(p_ZL14storage_matrix_90_load),
    .din12(p_ZL14storage_matrix_98_load),
    .din13(p_ZL14storage_matrix_106_load),
    .din14(p_ZL14storage_matrix_114_load),
    .din15(p_ZL14storage_matrix_122_load),
    .din16(p_ZL14storage_matrix_130_load),
    .din17(p_ZL14storage_matrix_138_load),
    .din18(p_ZL14storage_matrix_146_load),
    .din19(p_ZL14storage_matrix_154_load),
    .din20(p_ZL14storage_matrix_162_load),
    .din21(p_ZL14storage_matrix_170_load),
    .din22(p_ZL14storage_matrix_178_load),
    .din23(p_ZL14storage_matrix_186_load),
    .din24(p_ZL14storage_matrix_194_load),
    .din25(p_ZL14storage_matrix_202_load),
    .din26(p_ZL14storage_matrix_210_load),
    .din27(p_ZL14storage_matrix_218_load),
    .din28(p_ZL14storage_matrix_226_load),
    .din29(p_ZL14storage_matrix_234_load),
    .din30(p_ZL14storage_matrix_242_load),
    .din31(p_ZL14storage_matrix_250_load),
    .din32(trunc_ln58_fu_2388_p1),
    .dout(tmp_3_fu_2532_p34)
);

spiking_binam_mux_325_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 1 ),
    .din17_WIDTH( 1 ),
    .din18_WIDTH( 1 ),
    .din19_WIDTH( 1 ),
    .din20_WIDTH( 1 ),
    .din21_WIDTH( 1 ),
    .din22_WIDTH( 1 ),
    .din23_WIDTH( 1 ),
    .din24_WIDTH( 1 ),
    .din25_WIDTH( 1 ),
    .din26_WIDTH( 1 ),
    .din27_WIDTH( 1 ),
    .din28_WIDTH( 1 ),
    .din29_WIDTH( 1 ),
    .din30_WIDTH( 1 ),
    .din31_WIDTH( 1 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 1 ))
mux_325_1_1_1_U20(
    .din0(p_ZL14storage_matrix_3_load),
    .din1(p_ZL14storage_matrix_11_load),
    .din2(p_ZL14storage_matrix_19_load),
    .din3(p_ZL14storage_matrix_27_load),
    .din4(p_ZL14storage_matrix_35_load),
    .din5(p_ZL14storage_matrix_43_load),
    .din6(p_ZL14storage_matrix_51_load),
    .din7(p_ZL14storage_matrix_59_load),
    .din8(p_ZL14storage_matrix_67_load),
    .din9(p_ZL14storage_matrix_75_load),
    .din10(p_ZL14storage_matrix_83_load),
    .din11(p_ZL14storage_matrix_91_load),
    .din12(p_ZL14storage_matrix_99_load),
    .din13(p_ZL14storage_matrix_107_load),
    .din14(p_ZL14storage_matrix_115_load),
    .din15(p_ZL14storage_matrix_123_load),
    .din16(p_ZL14storage_matrix_131_load),
    .din17(p_ZL14storage_matrix_139_load),
    .din18(p_ZL14storage_matrix_147_load),
    .din19(p_ZL14storage_matrix_155_load),
    .din20(p_ZL14storage_matrix_163_load),
    .din21(p_ZL14storage_matrix_171_load),
    .din22(p_ZL14storage_matrix_179_load),
    .din23(p_ZL14storage_matrix_187_load),
    .din24(p_ZL14storage_matrix_195_load),
    .din25(p_ZL14storage_matrix_203_load),
    .din26(p_ZL14storage_matrix_211_load),
    .din27(p_ZL14storage_matrix_219_load),
    .din28(p_ZL14storage_matrix_227_load),
    .din29(p_ZL14storage_matrix_235_load),
    .din30(p_ZL14storage_matrix_243_load),
    .din31(p_ZL14storage_matrix_251_load),
    .din32(trunc_ln58_fu_2388_p1),
    .dout(tmp_4_fu_2602_p34)
);

spiking_binam_mux_325_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 1 ),
    .din17_WIDTH( 1 ),
    .din18_WIDTH( 1 ),
    .din19_WIDTH( 1 ),
    .din20_WIDTH( 1 ),
    .din21_WIDTH( 1 ),
    .din22_WIDTH( 1 ),
    .din23_WIDTH( 1 ),
    .din24_WIDTH( 1 ),
    .din25_WIDTH( 1 ),
    .din26_WIDTH( 1 ),
    .din27_WIDTH( 1 ),
    .din28_WIDTH( 1 ),
    .din29_WIDTH( 1 ),
    .din30_WIDTH( 1 ),
    .din31_WIDTH( 1 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 1 ))
mux_325_1_1_1_U21(
    .din0(p_ZL14storage_matrix_4_load),
    .din1(p_ZL14storage_matrix_12_load),
    .din2(p_ZL14storage_matrix_20_load),
    .din3(p_ZL14storage_matrix_28_load),
    .din4(p_ZL14storage_matrix_36_load),
    .din5(p_ZL14storage_matrix_44_load),
    .din6(p_ZL14storage_matrix_52_load),
    .din7(p_ZL14storage_matrix_60_load),
    .din8(p_ZL14storage_matrix_68_load),
    .din9(p_ZL14storage_matrix_76_load),
    .din10(p_ZL14storage_matrix_84_load),
    .din11(p_ZL14storage_matrix_92_load),
    .din12(p_ZL14storage_matrix_100_load),
    .din13(p_ZL14storage_matrix_108_load),
    .din14(p_ZL14storage_matrix_116_load),
    .din15(p_ZL14storage_matrix_124_load),
    .din16(p_ZL14storage_matrix_132_load),
    .din17(p_ZL14storage_matrix_140_load),
    .din18(p_ZL14storage_matrix_148_load),
    .din19(p_ZL14storage_matrix_156_load),
    .din20(p_ZL14storage_matrix_164_load),
    .din21(p_ZL14storage_matrix_172_load),
    .din22(p_ZL14storage_matrix_180_load),
    .din23(p_ZL14storage_matrix_188_load),
    .din24(p_ZL14storage_matrix_196_load),
    .din25(p_ZL14storage_matrix_204_load),
    .din26(p_ZL14storage_matrix_212_load),
    .din27(p_ZL14storage_matrix_220_load),
    .din28(p_ZL14storage_matrix_228_load),
    .din29(p_ZL14storage_matrix_236_load),
    .din30(p_ZL14storage_matrix_244_load),
    .din31(p_ZL14storage_matrix_252_load),
    .din32(trunc_ln58_fu_2388_p1),
    .dout(tmp_5_fu_2672_p34)
);

spiking_binam_mux_325_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 1 ),
    .din17_WIDTH( 1 ),
    .din18_WIDTH( 1 ),
    .din19_WIDTH( 1 ),
    .din20_WIDTH( 1 ),
    .din21_WIDTH( 1 ),
    .din22_WIDTH( 1 ),
    .din23_WIDTH( 1 ),
    .din24_WIDTH( 1 ),
    .din25_WIDTH( 1 ),
    .din26_WIDTH( 1 ),
    .din27_WIDTH( 1 ),
    .din28_WIDTH( 1 ),
    .din29_WIDTH( 1 ),
    .din30_WIDTH( 1 ),
    .din31_WIDTH( 1 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 1 ))
mux_325_1_1_1_U22(
    .din0(p_ZL14storage_matrix_5_load),
    .din1(p_ZL14storage_matrix_13_load),
    .din2(p_ZL14storage_matrix_21_load),
    .din3(p_ZL14storage_matrix_29_load),
    .din4(p_ZL14storage_matrix_37_load),
    .din5(p_ZL14storage_matrix_45_load),
    .din6(p_ZL14storage_matrix_53_load),
    .din7(p_ZL14storage_matrix_61_load),
    .din8(p_ZL14storage_matrix_69_load),
    .din9(p_ZL14storage_matrix_77_load),
    .din10(p_ZL14storage_matrix_85_load),
    .din11(p_ZL14storage_matrix_93_load),
    .din12(p_ZL14storage_matrix_101_load),
    .din13(p_ZL14storage_matrix_109_load),
    .din14(p_ZL14storage_matrix_117_load),
    .din15(p_ZL14storage_matrix_125_load),
    .din16(p_ZL14storage_matrix_133_load),
    .din17(p_ZL14storage_matrix_141_load),
    .din18(p_ZL14storage_matrix_149_load),
    .din19(p_ZL14storage_matrix_157_load),
    .din20(p_ZL14storage_matrix_165_load),
    .din21(p_ZL14storage_matrix_173_load),
    .din22(p_ZL14storage_matrix_181_load),
    .din23(p_ZL14storage_matrix_189_load),
    .din24(p_ZL14storage_matrix_197_load),
    .din25(p_ZL14storage_matrix_205_load),
    .din26(p_ZL14storage_matrix_213_load),
    .din27(p_ZL14storage_matrix_221_load),
    .din28(p_ZL14storage_matrix_229_load),
    .din29(p_ZL14storage_matrix_237_load),
    .din30(p_ZL14storage_matrix_245_load),
    .din31(p_ZL14storage_matrix_253_load),
    .din32(trunc_ln58_fu_2388_p1),
    .dout(tmp_7_fu_2742_p34)
);

spiking_binam_mux_325_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 1 ),
    .din17_WIDTH( 1 ),
    .din18_WIDTH( 1 ),
    .din19_WIDTH( 1 ),
    .din20_WIDTH( 1 ),
    .din21_WIDTH( 1 ),
    .din22_WIDTH( 1 ),
    .din23_WIDTH( 1 ),
    .din24_WIDTH( 1 ),
    .din25_WIDTH( 1 ),
    .din26_WIDTH( 1 ),
    .din27_WIDTH( 1 ),
    .din28_WIDTH( 1 ),
    .din29_WIDTH( 1 ),
    .din30_WIDTH( 1 ),
    .din31_WIDTH( 1 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 1 ))
mux_325_1_1_1_U23(
    .din0(p_ZL14storage_matrix_6_load),
    .din1(p_ZL14storage_matrix_14_load),
    .din2(p_ZL14storage_matrix_22_load),
    .din3(p_ZL14storage_matrix_30_load),
    .din4(p_ZL14storage_matrix_38_load),
    .din5(p_ZL14storage_matrix_46_load),
    .din6(p_ZL14storage_matrix_54_load),
    .din7(p_ZL14storage_matrix_62_load),
    .din8(p_ZL14storage_matrix_70_load),
    .din9(p_ZL14storage_matrix_78_load),
    .din10(p_ZL14storage_matrix_86_load),
    .din11(p_ZL14storage_matrix_94_load),
    .din12(p_ZL14storage_matrix_102_load),
    .din13(p_ZL14storage_matrix_110_load),
    .din14(p_ZL14storage_matrix_118_load),
    .din15(p_ZL14storage_matrix_126_load),
    .din16(p_ZL14storage_matrix_134_load),
    .din17(p_ZL14storage_matrix_142_load),
    .din18(p_ZL14storage_matrix_150_load),
    .din19(p_ZL14storage_matrix_158_load),
    .din20(p_ZL14storage_matrix_166_load),
    .din21(p_ZL14storage_matrix_174_load),
    .din22(p_ZL14storage_matrix_182_load),
    .din23(p_ZL14storage_matrix_190_load),
    .din24(p_ZL14storage_matrix_198_load),
    .din25(p_ZL14storage_matrix_206_load),
    .din26(p_ZL14storage_matrix_214_load),
    .din27(p_ZL14storage_matrix_222_load),
    .din28(p_ZL14storage_matrix_230_load),
    .din29(p_ZL14storage_matrix_238_load),
    .din30(p_ZL14storage_matrix_246_load),
    .din31(p_ZL14storage_matrix_254_load),
    .din32(trunc_ln58_fu_2388_p1),
    .dout(tmp_8_fu_2812_p34)
);

spiking_binam_mux_325_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 1 ),
    .din17_WIDTH( 1 ),
    .din18_WIDTH( 1 ),
    .din19_WIDTH( 1 ),
    .din20_WIDTH( 1 ),
    .din21_WIDTH( 1 ),
    .din22_WIDTH( 1 ),
    .din23_WIDTH( 1 ),
    .din24_WIDTH( 1 ),
    .din25_WIDTH( 1 ),
    .din26_WIDTH( 1 ),
    .din27_WIDTH( 1 ),
    .din28_WIDTH( 1 ),
    .din29_WIDTH( 1 ),
    .din30_WIDTH( 1 ),
    .din31_WIDTH( 1 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 1 ))
mux_325_1_1_1_U24(
    .din0(p_ZL14storage_matrix_7_load),
    .din1(p_ZL14storage_matrix_15_load),
    .din2(p_ZL14storage_matrix_23_load),
    .din3(p_ZL14storage_matrix_31_load),
    .din4(p_ZL14storage_matrix_39_load),
    .din5(p_ZL14storage_matrix_47_load),
    .din6(p_ZL14storage_matrix_55_load),
    .din7(p_ZL14storage_matrix_63_load),
    .din8(p_ZL14storage_matrix_71_load),
    .din9(p_ZL14storage_matrix_79_load),
    .din10(p_ZL14storage_matrix_87_load),
    .din11(p_ZL14storage_matrix_95_load),
    .din12(p_ZL14storage_matrix_103_load),
    .din13(p_ZL14storage_matrix_111_load),
    .din14(p_ZL14storage_matrix_119_load),
    .din15(p_ZL14storage_matrix_127_load),
    .din16(p_ZL14storage_matrix_135_load),
    .din17(p_ZL14storage_matrix_143_load),
    .din18(p_ZL14storage_matrix_151_load),
    .din19(p_ZL14storage_matrix_159_load),
    .din20(p_ZL14storage_matrix_167_load),
    .din21(p_ZL14storage_matrix_175_load),
    .din22(p_ZL14storage_matrix_183_load),
    .din23(p_ZL14storage_matrix_191_load),
    .din24(p_ZL14storage_matrix_199_load),
    .din25(p_ZL14storage_matrix_207_load),
    .din26(p_ZL14storage_matrix_215_load),
    .din27(p_ZL14storage_matrix_223_load),
    .din28(p_ZL14storage_matrix_231_load),
    .din29(p_ZL14storage_matrix_239_load),
    .din30(p_ZL14storage_matrix_247_load),
    .din31(p_ZL14storage_matrix_255_load),
    .din32(trunc_ln58_fu_2388_p1),
    .dout(tmp_9_fu_2882_p34)
);

spiking_binam_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln54_fu_2364_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            bank_fu_576 <= add_ln54_fu_2370_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            bank_fu_576 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        tmp_1_reg_3093_pp0_iter1_reg <= tmp_1_reg_3093;
        tmp_3_reg_3102_pp0_iter1_reg <= tmp_3_reg_3102;
        tmp_4_reg_3111_pp0_iter1_reg <= tmp_4_reg_3111;
        tmp_5_reg_3120_pp0_iter1_reg <= tmp_5_reg_3120;
        tmp_7_reg_3129_pp0_iter1_reg <= tmp_7_reg_3129;
        tmp_8_reg_3138_pp0_iter1_reg <= tmp_8_reg_3138;
        tmp_9_reg_3147_pp0_iter1_reg <= tmp_9_reg_3147;
        tmp_reg_3084_pp0_iter1_reg <= tmp_reg_3084;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_1_reg_3093 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1019_1_reg_3166 <= icmp_ln1019_1_fu_2963_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_reg_3102 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1019_2_reg_3176 <= icmp_ln1019_2_fu_2969_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_4_reg_3111 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1019_3_reg_3186 <= icmp_ln1019_3_fu_2975_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_5_reg_3120 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1019_4_reg_3196 <= icmp_ln1019_4_fu_2981_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_reg_3129 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1019_5_reg_3206 <= icmp_ln1019_5_fu_2987_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_8_reg_3138 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1019_6_reg_3216 <= icmp_ln1019_6_fu_2993_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_9_reg_3147 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1019_7_reg_3226 <= icmp_ln1019_7_fu_2999_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_3084 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1019_reg_3156 <= icmp_ln1019_fu_2957_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln54_fu_2364_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_1_reg_3093 <= tmp_1_fu_2462_p34;
        tmp_3_reg_3102 <= tmp_3_fu_2532_p34;
        tmp_4_reg_3111 <= tmp_4_fu_2602_p34;
        tmp_5_reg_3120 <= tmp_5_fu_2672_p34;
        tmp_7_reg_3129 <= tmp_7_fu_2742_p34;
        tmp_8_reg_3138 <= tmp_8_fu_2812_p34;
        tmp_9_reg_3147 <= tmp_9_fu_2882_p34;
        tmp_reg_3084 <= tmp_fu_2392_p34;
        zext_ln54_reg_3072[5 : 0] <= zext_ln54_fu_2376_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1019_1_fu_2963_p2 == 1'd1) & (tmp_1_reg_3093 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_V_1_addr_reg_3170 <= zext_ln54_reg_3072;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1019_2_fu_2969_p2 == 1'd1) & (tmp_3_reg_3102 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_V_2_addr_reg_3180 <= zext_ln54_reg_3072;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1019_3_fu_2975_p2 == 1'd1) & (tmp_4_reg_3111 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_V_3_addr_reg_3190 <= zext_ln54_reg_3072;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1019_4_fu_2981_p2 == 1'd1) & (tmp_5_reg_3120 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_V_4_addr_reg_3200 <= zext_ln54_reg_3072;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1019_5_fu_2987_p2 == 1'd1) & (tmp_7_reg_3129 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_V_5_addr_reg_3210 <= zext_ln54_reg_3072;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1019_6_fu_2993_p2 == 1'd1) & (tmp_8_reg_3138 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_V_6_addr_reg_3220 <= zext_ln54_reg_3072;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1019_7_fu_2999_p2 == 1'd1) & (tmp_9_reg_3147 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_V_7_addr_reg_3230 <= zext_ln54_reg_3072;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1019_fu_2957_p2 == 1'd1) & (tmp_reg_3084 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_V_addr_reg_3160 <= zext_ln54_reg_3072;
    end
end

always @ (*) begin
    if (((icmp_ln54_fu_2364_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_bank_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_bank_1 = bank_fu_576;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_1_ce0 = 1'b1;
    end else begin
        ref_timer_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_2_ce0 = 1'b1;
    end else begin
        ref_timer_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_3_ce0 = 1'b1;
    end else begin
        ref_timer_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_4_ce0 = 1'b1;
    end else begin
        ref_timer_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_5_ce0 = 1'b1;
    end else begin
        ref_timer_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_6_ce0 = 1'b1;
    end else begin
        ref_timer_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_7_ce0 = 1'b1;
    end else begin
        ref_timer_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_ce0 = 1'b1;
    end else begin
        ref_timer_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v_V_1_ce0 = 1'b1;
    end else begin
        v_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_V_1_ce1 = 1'b1;
    end else begin
        v_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1019_1_reg_3166 == 1'd1) & (tmp_1_reg_3093_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v_V_1_we0 = 1'b1;
    end else begin
        v_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v_V_2_ce0 = 1'b1;
    end else begin
        v_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_V_2_ce1 = 1'b1;
    end else begin
        v_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1019_2_reg_3176 == 1'd1) & (tmp_3_reg_3102_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v_V_2_we0 = 1'b1;
    end else begin
        v_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v_V_3_ce0 = 1'b1;
    end else begin
        v_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_V_3_ce1 = 1'b1;
    end else begin
        v_V_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1019_3_reg_3186 == 1'd1) & (tmp_4_reg_3111_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v_V_3_we0 = 1'b1;
    end else begin
        v_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v_V_4_ce0 = 1'b1;
    end else begin
        v_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_V_4_ce1 = 1'b1;
    end else begin
        v_V_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1019_4_reg_3196 == 1'd1) & (tmp_5_reg_3120_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v_V_4_we0 = 1'b1;
    end else begin
        v_V_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v_V_5_ce0 = 1'b1;
    end else begin
        v_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_V_5_ce1 = 1'b1;
    end else begin
        v_V_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1019_5_reg_3206 == 1'd1) & (tmp_7_reg_3129_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v_V_5_we0 = 1'b1;
    end else begin
        v_V_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v_V_6_ce0 = 1'b1;
    end else begin
        v_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_V_6_ce1 = 1'b1;
    end else begin
        v_V_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1019_6_reg_3216 == 1'd1) & (tmp_8_reg_3138_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v_V_6_we0 = 1'b1;
    end else begin
        v_V_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v_V_7_ce0 = 1'b1;
    end else begin
        v_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_V_7_ce1 = 1'b1;
    end else begin
        v_V_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1019_7_reg_3226 == 1'd1) & (tmp_9_reg_3147_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v_V_7_we0 = 1'b1;
    end else begin
        v_V_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v_V_ce0 = 1'b1;
    end else begin
        v_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v_V_ce1 = 1'b1;
    end else begin
        v_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1019_reg_3156 == 1'd1) & (tmp_reg_3084_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        v_V_we0 = 1'b1;
    end else begin
        v_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln54_fu_2370_p2 = (ap_sig_allocacmp_bank_1 + 6'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln1019_1_fu_2963_p2 = ((ref_timer_V_1_q0 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1019_2_fu_2969_p2 = ((ref_timer_V_2_q0 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1019_3_fu_2975_p2 = ((ref_timer_V_3_q0 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1019_4_fu_2981_p2 = ((ref_timer_V_4_q0 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1019_5_fu_2987_p2 = ((ref_timer_V_5_q0 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1019_6_fu_2993_p2 = ((ref_timer_V_6_q0 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1019_7_fu_2999_p2 = ((ref_timer_V_7_q0 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1019_fu_2957_p2 = ((ref_timer_V_q0 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln54_fu_2364_p2 = ((ap_sig_allocacmp_bank_1 == 6'd32) ? 1'b1 : 1'b0);

assign ref_timer_V_1_address0 = zext_ln54_fu_2376_p1;

assign ref_timer_V_2_address0 = zext_ln54_fu_2376_p1;

assign ref_timer_V_3_address0 = zext_ln54_fu_2376_p1;

assign ref_timer_V_4_address0 = zext_ln54_fu_2376_p1;

assign ref_timer_V_5_address0 = zext_ln54_fu_2376_p1;

assign ref_timer_V_6_address0 = zext_ln54_fu_2376_p1;

assign ref_timer_V_7_address0 = zext_ln54_fu_2376_p1;

assign ref_timer_V_address0 = zext_ln54_fu_2376_p1;

assign trunc_ln58_fu_2388_p1 = ap_sig_allocacmp_bank_1[4:0];

assign v_V_1_address0 = v_V_1_addr_reg_3170;

assign v_V_1_address1 = zext_ln54_reg_3072;

assign v_V_1_d0 = (v_V_1_q1 + 7'd13);

assign v_V_2_address0 = v_V_2_addr_reg_3180;

assign v_V_2_address1 = zext_ln54_reg_3072;

assign v_V_2_d0 = (v_V_2_q1 + 7'd13);

assign v_V_3_address0 = v_V_3_addr_reg_3190;

assign v_V_3_address1 = zext_ln54_reg_3072;

assign v_V_3_d0 = (v_V_3_q1 + 7'd13);

assign v_V_4_address0 = v_V_4_addr_reg_3200;

assign v_V_4_address1 = zext_ln54_reg_3072;

assign v_V_4_d0 = (v_V_4_q1 + 7'd13);

assign v_V_5_address0 = v_V_5_addr_reg_3210;

assign v_V_5_address1 = zext_ln54_reg_3072;

assign v_V_5_d0 = (v_V_5_q1 + 7'd13);

assign v_V_6_address0 = v_V_6_addr_reg_3220;

assign v_V_6_address1 = zext_ln54_reg_3072;

assign v_V_6_d0 = (v_V_6_q1 + 7'd13);

assign v_V_7_address0 = v_V_7_addr_reg_3230;

assign v_V_7_address1 = zext_ln54_reg_3072;

assign v_V_7_d0 = (v_V_7_q1 + 7'd13);

assign v_V_address0 = v_V_addr_reg_3160;

assign v_V_address1 = zext_ln54_reg_3072;

assign v_V_d0 = (v_V_q1 + 7'd13);

assign zext_ln54_fu_2376_p1 = ap_sig_allocacmp_bank_1;

always @ (posedge ap_clk) begin
    zext_ln54_reg_3072[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_54_4
