// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_70_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ref_timer_V_7_address0,
        ref_timer_V_7_ce0,
        ref_timer_V_7_we0,
        ref_timer_V_7_d0,
        ref_timer_V_7_address1,
        ref_timer_V_7_ce1,
        ref_timer_V_7_q1,
        ref_timer_V_6_address0,
        ref_timer_V_6_ce0,
        ref_timer_V_6_we0,
        ref_timer_V_6_d0,
        ref_timer_V_6_address1,
        ref_timer_V_6_ce1,
        ref_timer_V_6_q1,
        ref_timer_V_5_address0,
        ref_timer_V_5_ce0,
        ref_timer_V_5_we0,
        ref_timer_V_5_d0,
        ref_timer_V_5_address1,
        ref_timer_V_5_ce1,
        ref_timer_V_5_q1,
        ref_timer_V_4_address0,
        ref_timer_V_4_ce0,
        ref_timer_V_4_we0,
        ref_timer_V_4_d0,
        ref_timer_V_4_address1,
        ref_timer_V_4_ce1,
        ref_timer_V_4_q1,
        ref_timer_V_3_address0,
        ref_timer_V_3_ce0,
        ref_timer_V_3_we0,
        ref_timer_V_3_d0,
        ref_timer_V_3_address1,
        ref_timer_V_3_ce1,
        ref_timer_V_3_q1,
        ref_timer_V_2_address0,
        ref_timer_V_2_ce0,
        ref_timer_V_2_we0,
        ref_timer_V_2_d0,
        ref_timer_V_2_address1,
        ref_timer_V_2_ce1,
        ref_timer_V_2_q1,
        ref_timer_V_1_address0,
        ref_timer_V_1_ce0,
        ref_timer_V_1_we0,
        ref_timer_V_1_d0,
        ref_timer_V_1_address1,
        ref_timer_V_1_ce1,
        ref_timer_V_1_q1,
        ref_timer_V_address0,
        ref_timer_V_ce0,
        ref_timer_V_we0,
        ref_timer_V_d0,
        ref_timer_V_address1,
        ref_timer_V_ce1,
        ref_timer_V_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] ref_timer_V_7_address0;
output   ref_timer_V_7_ce0;
output   ref_timer_V_7_we0;
output  [2:0] ref_timer_V_7_d0;
output  [4:0] ref_timer_V_7_address1;
output   ref_timer_V_7_ce1;
input  [2:0] ref_timer_V_7_q1;
output  [4:0] ref_timer_V_6_address0;
output   ref_timer_V_6_ce0;
output   ref_timer_V_6_we0;
output  [2:0] ref_timer_V_6_d0;
output  [4:0] ref_timer_V_6_address1;
output   ref_timer_V_6_ce1;
input  [2:0] ref_timer_V_6_q1;
output  [4:0] ref_timer_V_5_address0;
output   ref_timer_V_5_ce0;
output   ref_timer_V_5_we0;
output  [2:0] ref_timer_V_5_d0;
output  [4:0] ref_timer_V_5_address1;
output   ref_timer_V_5_ce1;
input  [2:0] ref_timer_V_5_q1;
output  [4:0] ref_timer_V_4_address0;
output   ref_timer_V_4_ce0;
output   ref_timer_V_4_we0;
output  [2:0] ref_timer_V_4_d0;
output  [4:0] ref_timer_V_4_address1;
output   ref_timer_V_4_ce1;
input  [2:0] ref_timer_V_4_q1;
output  [4:0] ref_timer_V_3_address0;
output   ref_timer_V_3_ce0;
output   ref_timer_V_3_we0;
output  [2:0] ref_timer_V_3_d0;
output  [4:0] ref_timer_V_3_address1;
output   ref_timer_V_3_ce1;
input  [2:0] ref_timer_V_3_q1;
output  [4:0] ref_timer_V_2_address0;
output   ref_timer_V_2_ce0;
output   ref_timer_V_2_we0;
output  [2:0] ref_timer_V_2_d0;
output  [4:0] ref_timer_V_2_address1;
output   ref_timer_V_2_ce1;
input  [2:0] ref_timer_V_2_q1;
output  [4:0] ref_timer_V_1_address0;
output   ref_timer_V_1_ce0;
output   ref_timer_V_1_we0;
output  [2:0] ref_timer_V_1_d0;
output  [4:0] ref_timer_V_1_address1;
output   ref_timer_V_1_ce1;
input  [2:0] ref_timer_V_1_q1;
output  [4:0] ref_timer_V_address0;
output   ref_timer_V_ce0;
output   ref_timer_V_we0;
output  [2:0] ref_timer_V_d0;
output  [4:0] ref_timer_V_address1;
output   ref_timer_V_ce1;
input  [2:0] ref_timer_V_q1;

reg ap_idle;
reg ref_timer_V_7_ce0;
reg ref_timer_V_7_we0;
reg ref_timer_V_7_ce1;
reg ref_timer_V_6_ce0;
reg ref_timer_V_6_we0;
reg ref_timer_V_6_ce1;
reg ref_timer_V_5_ce0;
reg ref_timer_V_5_we0;
reg ref_timer_V_5_ce1;
reg ref_timer_V_4_ce0;
reg ref_timer_V_4_we0;
reg ref_timer_V_4_ce1;
reg ref_timer_V_3_ce0;
reg ref_timer_V_3_we0;
reg ref_timer_V_3_ce1;
reg ref_timer_V_2_ce0;
reg ref_timer_V_2_we0;
reg ref_timer_V_2_ce1;
reg ref_timer_V_1_ce0;
reg ref_timer_V_1_we0;
reg ref_timer_V_1_ce1;
reg ref_timer_V_ce0;
reg ref_timer_V_we0;
reg ref_timer_V_ce1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln70_fu_212_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [4:0] ref_timer_V_addr_reg_306;
wire    ap_block_pp0_stage0_11001;
reg   [4:0] ref_timer_V_1_addr_reg_312;
reg   [4:0] ref_timer_V_2_addr_reg_318;
reg   [4:0] ref_timer_V_3_addr_reg_324;
reg   [4:0] ref_timer_V_4_addr_reg_330;
reg   [4:0] ref_timer_V_5_addr_reg_336;
reg   [4:0] ref_timer_V_6_addr_reg_342;
reg   [4:0] ref_timer_V_7_addr_reg_348;
wire   [2:0] trunc_ln1035_fu_246_p1;
reg   [2:0] trunc_ln1035_reg_354;
wire   [63:0] zext_ln1035_fu_234_p1;
wire    ap_block_pp0_stage0;
reg   [8:0] i_1_fu_64;
wire   [8:0] add_ln70_fu_218_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_i;
wire   [0:0] icmp_ln1035_fu_276_p2;
wire   [2:0] add_ln841_fu_282_p2;
wire   [4:0] lshr_ln1_fu_224_p4;
wire   [2:0] tmp_2_fu_255_p10;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

spiking_binam_mux_83_3_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 3 ),
    .din2_WIDTH( 3 ),
    .din3_WIDTH( 3 ),
    .din4_WIDTH( 3 ),
    .din5_WIDTH( 3 ),
    .din6_WIDTH( 3 ),
    .din7_WIDTH( 3 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 3 ))
mux_83_3_1_1_U298(
    .din0(ref_timer_V_q1),
    .din1(ref_timer_V_1_q1),
    .din2(ref_timer_V_2_q1),
    .din3(ref_timer_V_3_q1),
    .din4(ref_timer_V_4_q1),
    .din5(ref_timer_V_5_q1),
    .din6(ref_timer_V_6_q1),
    .din7(ref_timer_V_7_q1),
    .din8(trunc_ln1035_reg_354),
    .dout(tmp_2_fu_255_p10)
);

spiking_binam_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln70_fu_212_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_1_fu_64 <= add_ln70_fu_218_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_64 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln70_fu_212_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_1_addr_reg_312 <= zext_ln1035_fu_234_p1;
        ref_timer_V_2_addr_reg_318 <= zext_ln1035_fu_234_p1;
        ref_timer_V_3_addr_reg_324 <= zext_ln1035_fu_234_p1;
        ref_timer_V_4_addr_reg_330 <= zext_ln1035_fu_234_p1;
        ref_timer_V_5_addr_reg_336 <= zext_ln1035_fu_234_p1;
        ref_timer_V_6_addr_reg_342 <= zext_ln1035_fu_234_p1;
        ref_timer_V_7_addr_reg_348 <= zext_ln1035_fu_234_p1;
        ref_timer_V_addr_reg_306 <= zext_ln1035_fu_234_p1;
        trunc_ln1035_reg_354 <= trunc_ln1035_fu_246_p1;
    end
end

always @ (*) begin
    if (((icmp_ln70_fu_212_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 9'd0;
    end else begin
        ap_sig_allocacmp_i = i_1_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_1_ce0 = 1'b1;
    end else begin
        ref_timer_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_1_ce1 = 1'b1;
    end else begin
        ref_timer_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1035_fu_276_p2 == 1'd0) & (trunc_ln1035_reg_354 == 3'd1))) begin
        ref_timer_V_1_we0 = 1'b1;
    end else begin
        ref_timer_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_2_ce0 = 1'b1;
    end else begin
        ref_timer_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_2_ce1 = 1'b1;
    end else begin
        ref_timer_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1035_fu_276_p2 == 1'd0) & (trunc_ln1035_reg_354 == 3'd2))) begin
        ref_timer_V_2_we0 = 1'b1;
    end else begin
        ref_timer_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_3_ce0 = 1'b1;
    end else begin
        ref_timer_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_3_ce1 = 1'b1;
    end else begin
        ref_timer_V_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1035_fu_276_p2 == 1'd0) & (trunc_ln1035_reg_354 == 3'd3))) begin
        ref_timer_V_3_we0 = 1'b1;
    end else begin
        ref_timer_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_4_ce0 = 1'b1;
    end else begin
        ref_timer_V_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_4_ce1 = 1'b1;
    end else begin
        ref_timer_V_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1035_fu_276_p2 == 1'd0) & (trunc_ln1035_reg_354 == 3'd4))) begin
        ref_timer_V_4_we0 = 1'b1;
    end else begin
        ref_timer_V_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_5_ce0 = 1'b1;
    end else begin
        ref_timer_V_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_5_ce1 = 1'b1;
    end else begin
        ref_timer_V_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1035_fu_276_p2 == 1'd0) & (trunc_ln1035_reg_354 == 3'd5))) begin
        ref_timer_V_5_we0 = 1'b1;
    end else begin
        ref_timer_V_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_6_ce0 = 1'b1;
    end else begin
        ref_timer_V_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_6_ce1 = 1'b1;
    end else begin
        ref_timer_V_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1035_fu_276_p2 == 1'd0) & (trunc_ln1035_reg_354 == 3'd6))) begin
        ref_timer_V_6_we0 = 1'b1;
    end else begin
        ref_timer_V_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_7_ce0 = 1'b1;
    end else begin
        ref_timer_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_7_ce1 = 1'b1;
    end else begin
        ref_timer_V_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1035_fu_276_p2 == 1'd0) & (trunc_ln1035_reg_354 == 3'd7))) begin
        ref_timer_V_7_we0 = 1'b1;
    end else begin
        ref_timer_V_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_ce0 = 1'b1;
    end else begin
        ref_timer_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ref_timer_V_ce1 = 1'b1;
    end else begin
        ref_timer_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1035_fu_276_p2 == 1'd0) & (trunc_ln1035_reg_354 == 3'd0))) begin
        ref_timer_V_we0 = 1'b1;
    end else begin
        ref_timer_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln70_fu_218_p2 = (ap_sig_allocacmp_i + 9'd1);

assign add_ln841_fu_282_p2 = (tmp_2_fu_255_p10 + 3'd7);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln1035_fu_276_p2 = ((tmp_2_fu_255_p10 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln70_fu_212_p2 = ((ap_sig_allocacmp_i == 9'd256) ? 1'b1 : 1'b0);

assign lshr_ln1_fu_224_p4 = {{ap_sig_allocacmp_i[7:3]}};

assign ref_timer_V_1_address0 = ref_timer_V_1_addr_reg_312;

assign ref_timer_V_1_address1 = zext_ln1035_fu_234_p1;

assign ref_timer_V_1_d0 = add_ln841_fu_282_p2;

assign ref_timer_V_2_address0 = ref_timer_V_2_addr_reg_318;

assign ref_timer_V_2_address1 = zext_ln1035_fu_234_p1;

assign ref_timer_V_2_d0 = add_ln841_fu_282_p2;

assign ref_timer_V_3_address0 = ref_timer_V_3_addr_reg_324;

assign ref_timer_V_3_address1 = zext_ln1035_fu_234_p1;

assign ref_timer_V_3_d0 = add_ln841_fu_282_p2;

assign ref_timer_V_4_address0 = ref_timer_V_4_addr_reg_330;

assign ref_timer_V_4_address1 = zext_ln1035_fu_234_p1;

assign ref_timer_V_4_d0 = add_ln841_fu_282_p2;

assign ref_timer_V_5_address0 = ref_timer_V_5_addr_reg_336;

assign ref_timer_V_5_address1 = zext_ln1035_fu_234_p1;

assign ref_timer_V_5_d0 = add_ln841_fu_282_p2;

assign ref_timer_V_6_address0 = ref_timer_V_6_addr_reg_342;

assign ref_timer_V_6_address1 = zext_ln1035_fu_234_p1;

assign ref_timer_V_6_d0 = add_ln841_fu_282_p2;

assign ref_timer_V_7_address0 = ref_timer_V_7_addr_reg_348;

assign ref_timer_V_7_address1 = zext_ln1035_fu_234_p1;

assign ref_timer_V_7_d0 = add_ln841_fu_282_p2;

assign ref_timer_V_address0 = ref_timer_V_addr_reg_306;

assign ref_timer_V_address1 = zext_ln1035_fu_234_p1;

assign ref_timer_V_d0 = add_ln841_fu_282_p2;

assign trunc_ln1035_fu_246_p1 = ap_sig_allocacmp_i[2:0];

assign zext_ln1035_fu_234_p1 = lshr_ln1_fu_224_p4;

endmodule //spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_70_6
