# ==============================================================
# Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
# Tool Version Limit: 2019.12
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# ==============================================================
source ./settings.tcl
source -notrace ./extraction.tcl

set vivado_proj_name project
set vivado_proj_dir .
set target_device "${device}${package}${speed}"
set target_clk_period_ns "10"
set target_clk_freq_hz [expr {floor(1000 / $target_clk_period_ns) * 1000000}]
set ip_vlnv xilinx.com:hls:spiking_binam:1.0
set ip_repo_path ../ip
set bd_design_name bd_0
set bd_inst_name hls_inst
set bd_props {}

set has_synth true
set synth_design_args {-directive sdx_optimization_effort_high}
set synth_dcp ""
set synth_props {}

set has_impl false
set impl_props {}

set report_options [dict create]
dict set report_options report_level 2
dict set report_options report_max_paths 10
dict set report_options stdout_hls_reports 1
dict set report_options stdout_vivado_reports 0
dict set report_options hls_project SpikingBINAM
dict set report_options hls_solution solution1
dict set report_options has_synth $has_synth
dict set report_options has_impl $has_impl
dict set report_options vivado_reportbasename $top_module
dict set report_options vivado_reportdir ./report
dict set report_options hls_impl_dir ..
dict set report_options hls_reportdir ../report/$language
dict set report_options target_clk_period $target_clk_period_ns
dict set report_options target_device $target_device
dict set report_options language $language
dict set report_options clock_name $clock
dict set report_options error_if_impl_timing_fails false
dict set report_options bindmodules {spiking_binam_flow_control_loop_pipe_sequential_init spiking_binam_mux_325_1_1_1 spiking_binam_mux_83_3_1_1 spiking_binam_mux_83_7_1_1 spiking_binam_mul_6ns_5ns_7_1_1 spiking_binam_p_ZL14storage_matrix_0_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_8_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_16_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_24_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_32_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_40_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_48_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_56_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_64_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_72_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_80_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_88_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_96_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_104_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_112_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_120_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_128_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_136_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_144_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_152_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_160_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_168_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_176_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_184_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_192_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_200_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_208_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_216_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_224_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_232_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_240_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_248_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_1_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_9_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_17_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_25_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_33_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_41_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_49_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_57_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_65_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_73_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_81_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_89_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_97_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_105_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_113_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_121_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_129_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_137_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_145_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_153_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_161_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_169_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_177_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_185_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_193_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_201_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_209_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_217_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_225_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_233_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_241_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_249_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_2_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_10_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_18_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_26_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_34_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_42_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_50_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_58_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_66_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_74_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_82_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_90_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_98_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_106_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_114_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_122_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_130_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_138_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_146_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_154_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_162_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_170_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_178_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_186_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_194_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_202_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_210_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_218_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_226_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_234_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_242_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_250_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_3_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_11_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_19_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_27_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_35_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_43_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_51_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_59_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_67_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_75_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_83_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_91_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_99_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_107_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_115_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_123_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_131_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_139_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_147_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_155_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_163_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_171_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_179_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_187_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_195_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_203_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_211_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_219_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_227_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_235_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_243_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_251_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_4_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_12_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_20_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_28_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_36_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_44_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_52_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_60_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_68_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_76_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_84_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_92_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_100_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_108_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_116_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_124_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_132_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_140_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_148_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_156_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_164_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_172_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_180_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_188_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_196_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_204_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_212_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_220_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_228_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_236_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_244_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_252_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_5_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_13_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_21_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_29_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_37_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_45_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_53_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_61_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_69_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_77_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_85_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_93_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_101_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_109_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_117_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_125_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_133_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_141_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_149_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_157_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_165_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_173_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_181_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_189_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_197_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_205_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_213_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_221_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_229_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_237_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_245_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_253_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_6_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_14_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_22_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_30_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_38_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_46_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_54_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_62_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_70_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_78_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_86_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_94_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_102_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_110_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_118_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_126_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_134_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_142_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_150_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_158_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_166_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_174_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_182_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_190_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_198_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_206_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_214_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_222_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_230_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_238_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_246_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_254_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_7_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_15_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_23_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_31_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_39_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_47_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_55_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_63_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_71_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_79_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_87_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_95_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_103_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_111_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_119_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_127_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_135_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_143_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_151_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_159_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_167_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_175_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_183_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_191_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_199_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_207_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_215_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_223_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_231_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_239_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_247_ROM_AUTO_1R spiking_binam_p_ZL14storage_matrix_255_ROM_AUTO_1R spiking_binam_v_V_RAM_AUTO_1R1W spiking_binam_ref_timer_V_RAM_AUTO_1R1W spiking_binam_CTRL_s_axi spiking_binam_regslice_both}
dict set report_options max_module_depth 6


create_project $vivado_proj_name $vivado_proj_dir -part $target_device -force
set_property target_language $language [current_project]


# setup design sources and constraints

if { ![file exists $ip_repo_path] } {
  error "Cannot find packaged HLS IP"
}
set_property ip_repo_paths [file normalize $ip_repo_path] [current_project]
update_ip_catalog
create_bd_design $bd_design_name

# Instantiate HLS IP
set cell_inst [create_bd_cell -type ip -vlnv $ip_vlnv $bd_inst_name]
if { [llength $bd_props] } { 
  set_property -dict $bd_props $cell_inst 
}

# Update BD pins
make_bd_pins_external $cell_inst
make_bd_intf_pins_external $cell_inst

# Set BD clock port freq property
set bd_clk_ports [get_bd_ports -filter {TYPE==clk}]
if { [llength $bd_clk_ports] && $target_clk_freq_hz ne "" } { 
  set_property CONFIG.FREQ_HZ $target_clk_freq_hz $bd_clk_ports 
}

# Remove "_0" suffix from BD ports & interfaces so they match IP ports (XDC names will match)
foreach bd_port [get_bd_intf_ports] {
  set_property name [regsub {_0$} [get_property name $bd_port] {}] $bd_port
}
foreach bd_port [get_bd_ports -filter {INTF!=TRUE}] {
  set_property name [regsub {_0$} [get_property name $bd_port] {}] $bd_port
}

# Vitis kernels have minimum width for s_axi target address space 
# This changes external port address space, not IP
set s_axi_addr_width_min 32
foreach bd_port [get_bd_intf_ports -filter {MODE == "Slave" && VLNV =~ "xilinx.com:interface:aximm_rtl:*"}] {
  set bd_port_addr_width [get_property CONFIG.ADDR_WIDTH $bd_port]
  if { $bd_port_addr_width < $s_axi_addr_width_min } {
    puts "INFO: Updating $bd_port CONFIG.ADDR_WIDTH to $s_axi_addr_width_min"
    set_property CONFIG.ADDR_WIDTH $s_axi_addr_width_min $bd_port
  }
}

# Downgrade slave segment critical warnings since this is an OOC design
set_msg_config -id {[BD 41-1265]} -severity {CRITICAL WARNING} -new_severity {INFO}

# Use default address assignment
assign_bd_address

# Set top of design to use BD wrapper
set toprtl [make_wrapper -files [get_files ${bd_design_name}.bd] -top]
add_files -norecurse $toprtl
set top_inst_name [file root [file tail $toprtl]]
puts "Using BD top: $top_inst_name"

# Add XDC files
set xdc_files [glob -nocomplain ./*.xdc]
if { [llength $xdc_files] } {
    add_files -fileset constrs_1 -norecurse $xdc_files
}

# Create the ooc run objects without running them
launch_runs synth_1 -scripts_only

# Rest all the synthesis runs
foreach run [get_runs -filter {IS_SYNTHESIS == 1}] {
  reset_run [get_runs $run]
}


set_property XPM_LIBRARIES {XPM_MEMORY XPM_FIFO} [current_project]

hls_vivado_reports_setup $report_options
if { $has_synth || $has_impl } {
  # synth properties setting
  set_property -name {STEPS.SYNTH_DESIGN.ARGS.MORE OPTIONS} -value {-mode out_of_context} -objects [get_runs synth_1]
  set ip_inst [get_ips -quiet ${bd_design_name}*${bd_inst_name}*]
  if { ![llength $ip_inst] } {
      error "Cannot find HLS IP instance: ${bd_design_name}*${bd_inst_name}*"
  }
  set synth_run [get_runs -filter {IS_SYNTHESIS == 1} ${ip_inst}*]
  if { ![llength $synth_run] } {
      error "Cannot find synth run for HLS IP: ${ip_inst}*"
  }

  if { [llength $synth_design_args] } {
      set_property -name {STEPS.SYNTH_DESIGN.ARGS.MORE OPTIONS} -value $synth_design_args -objects $synth_run
  }

  if { [llength $synth_props] } {
    set_property -dict $synth_props $synth_run
  }

  # launch run synth
  launch_runs synth_1
  wait_on_run synth_1
  # synth reports
  hls_vivado_reports_synth synth_1 $report_options
  if { $synth_dcp ne "" } {
    file mkdir [file dirname $synth_dcp]
    set run_dcp [glob -nocomplain [get_property DIRECTORY $synth_run]/*.dcp]
    if { [llength $run_dcp] != 1 } { error "Cannot find single dcp file for run $synth_run" }
    file copy -force $run_dcp $synth_dcp
  }
}


if { $has_impl } {
  # launch run impl
  if { [llength $impl_props] } {
    set_property -dict $impl_props [get_runs impl_1]
  }
  launch_runs impl_1
  wait_on_run impl_1
  # impl reports
  hls_vivado_reports_impl impl_1 $report_options
}
hls_vivado_reports_finalize $report_options
