// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_52_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        cur_id_V_5,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_address0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_q0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_address0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_we0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_d0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_address1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_q1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_address0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_q0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_address0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_we0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_d0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_address1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_q1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_address0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_q0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_address0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_we0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_d0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_address1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_q1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_address0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_q0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_address0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_we0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_d0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_address1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_q1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_address0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_q0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_address0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_we0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_d0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_address1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_q1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_address0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_q0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_address0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_we0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_d0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_address1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_q1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_address0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_q0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_address0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_we0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_d0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_address1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_q1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_address0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_q0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_address0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_we0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_d0,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_address1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce1,
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] cur_id_V_5;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_address0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce0;
input  [2:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_q0;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_address0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_we0;
output  [6:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_d0;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_address1;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce1;
input  [6:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_q1;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_address0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce0;
input  [2:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_q0;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_address0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_we0;
output  [6:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_d0;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_address1;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce1;
input  [6:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_q1;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_address0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce0;
input  [2:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_q0;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_address0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_we0;
output  [6:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_d0;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_address1;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce1;
input  [6:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_q1;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_address0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce0;
input  [2:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_q0;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_address0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_we0;
output  [6:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_d0;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_address1;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce1;
input  [6:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_q1;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_address0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce0;
input  [2:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_q0;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_address0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_we0;
output  [6:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_d0;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_address1;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce1;
input  [6:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_q1;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_address0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce0;
input  [2:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_q0;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_address0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_we0;
output  [6:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_d0;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_address1;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce1;
input  [6:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_q1;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_address0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce0;
input  [2:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_q0;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_address0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_we0;
output  [6:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_d0;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_address1;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce1;
input  [6:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_q1;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_address0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce0;
input  [2:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_q0;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_address0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce0;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_we0;
output  [6:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_d0;
output  [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_address1;
output   spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce1;
input  [6:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_q1;

reg ap_idle;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_we0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce1;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_we0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce1;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_we0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce1;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_we0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce1;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_we0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce1;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_we0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce1;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_we0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce1;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_we0;
reg spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln52_fu_436_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [13:0] p_ZL14storage_matrix_3_address0;
reg    p_ZL14storage_matrix_3_ce0;
wire   [0:0] p_ZL14storage_matrix_3_q0;
wire   [13:0] p_ZL14storage_matrix_3_address1;
reg    p_ZL14storage_matrix_3_ce1;
wire   [0:0] p_ZL14storage_matrix_3_q1;
wire   [13:0] p_ZL14storage_matrix_2_address0;
reg    p_ZL14storage_matrix_2_ce0;
wire   [0:0] p_ZL14storage_matrix_2_q0;
wire   [13:0] p_ZL14storage_matrix_2_address1;
reg    p_ZL14storage_matrix_2_ce1;
wire   [0:0] p_ZL14storage_matrix_2_q1;
wire   [13:0] p_ZL14storage_matrix_1_address0;
reg    p_ZL14storage_matrix_1_ce0;
wire   [0:0] p_ZL14storage_matrix_1_q0;
wire   [13:0] p_ZL14storage_matrix_1_address1;
reg    p_ZL14storage_matrix_1_ce1;
wire   [0:0] p_ZL14storage_matrix_1_q1;
wire   [13:0] p_ZL14storage_matrix_0_address0;
reg    p_ZL14storage_matrix_0_ce0;
wire   [0:0] p_ZL14storage_matrix_0_q0;
wire   [13:0] p_ZL14storage_matrix_0_address1;
reg    p_ZL14storage_matrix_0_ce1;
wire   [0:0] p_ZL14storage_matrix_0_q1;
reg   [5:0] bank_1_reg_625;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln52_fu_503_p1;
reg   [63:0] zext_ln52_reg_674;
reg   [0:0] p_ZL14storage_matrix_0_load_reg_686;
reg   [0:0] p_ZL14storage_matrix_0_load_reg_686_pp0_iter2_reg;
reg   [0:0] p_ZL14storage_matrix_1_load_reg_695;
reg   [0:0] p_ZL14storage_matrix_1_load_reg_695_pp0_iter2_reg;
reg   [0:0] p_ZL14storage_matrix_2_load_reg_704;
reg   [0:0] p_ZL14storage_matrix_2_load_reg_704_pp0_iter2_reg;
reg   [0:0] p_ZL14storage_matrix_3_load_reg_713;
reg   [0:0] p_ZL14storage_matrix_3_load_reg_713_pp0_iter2_reg;
reg   [0:0] p_ZL14storage_matrix_0_load_1_reg_722;
reg   [0:0] p_ZL14storage_matrix_0_load_1_reg_722_pp0_iter2_reg;
reg   [0:0] p_ZL14storage_matrix_1_load_1_reg_731;
reg   [0:0] p_ZL14storage_matrix_1_load_1_reg_731_pp0_iter2_reg;
reg   [0:0] p_ZL14storage_matrix_2_load_1_reg_740;
reg   [0:0] p_ZL14storage_matrix_2_load_1_reg_740_pp0_iter2_reg;
reg   [0:0] p_ZL14storage_matrix_3_load_1_reg_749;
reg   [0:0] p_ZL14storage_matrix_3_load_1_reg_749_pp0_iter2_reg;
wire   [0:0] icmp_ln1019_fu_514_p2;
reg   [0:0] icmp_ln1019_reg_758;
reg   [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_addr_reg_762;
wire   [0:0] icmp_ln1019_1_fu_520_p2;
reg   [0:0] icmp_ln1019_1_reg_768;
reg   [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_addr_reg_772;
wire   [0:0] icmp_ln1019_2_fu_526_p2;
reg   [0:0] icmp_ln1019_2_reg_778;
reg   [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_addr_reg_782;
wire   [0:0] icmp_ln1019_3_fu_532_p2;
reg   [0:0] icmp_ln1019_3_reg_788;
reg   [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_addr_reg_792;
wire   [0:0] icmp_ln1019_4_fu_538_p2;
reg   [0:0] icmp_ln1019_4_reg_798;
reg   [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_addr_reg_802;
wire   [0:0] icmp_ln1019_5_fu_544_p2;
reg   [0:0] icmp_ln1019_5_reg_808;
reg   [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_addr_reg_812;
wire   [0:0] icmp_ln1019_6_fu_550_p2;
reg   [0:0] icmp_ln1019_6_reg_818;
reg   [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_addr_reg_822;
wire   [0:0] icmp_ln1019_7_fu_556_p2;
reg   [0:0] icmp_ln1019_7_reg_828;
reg   [4:0] spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_addr_reg_832;
wire   [63:0] zext_ln56_fu_468_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln56_1_fu_490_p1;
reg   [5:0] bank_fu_78;
wire   [5:0] add_ln52_fu_442_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_bank_1;
wire   [4:0] trunc_ln56_fu_448_p1;
wire   [13:0] tmp_4_fu_458_p4;
wire   [5:0] shl_ln56_fu_452_p2;
wire   [5:0] or_ln56_fu_476_p2;
wire   [13:0] tmp_6_fu_482_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
end

spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_52_4_p_ZL14storage_matrix_3_ROM_AUTO_1R #(
    .DataWidth( 1 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
p_ZL14storage_matrix_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL14storage_matrix_3_address0),
    .ce0(p_ZL14storage_matrix_3_ce0),
    .q0(p_ZL14storage_matrix_3_q0),
    .address1(p_ZL14storage_matrix_3_address1),
    .ce1(p_ZL14storage_matrix_3_ce1),
    .q1(p_ZL14storage_matrix_3_q1)
);

spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_52_4_p_ZL14storage_matrix_2_ROM_AUTO_1R #(
    .DataWidth( 1 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
p_ZL14storage_matrix_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL14storage_matrix_2_address0),
    .ce0(p_ZL14storage_matrix_2_ce0),
    .q0(p_ZL14storage_matrix_2_q0),
    .address1(p_ZL14storage_matrix_2_address1),
    .ce1(p_ZL14storage_matrix_2_ce1),
    .q1(p_ZL14storage_matrix_2_q1)
);

spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_52_4_p_ZL14storage_matrix_1_ROM_AUTO_1R #(
    .DataWidth( 1 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
p_ZL14storage_matrix_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL14storage_matrix_1_address0),
    .ce0(p_ZL14storage_matrix_1_ce0),
    .q0(p_ZL14storage_matrix_1_q0),
    .address1(p_ZL14storage_matrix_1_address1),
    .ce1(p_ZL14storage_matrix_1_ce1),
    .q1(p_ZL14storage_matrix_1_q1)
);

spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_52_4_p_ZL14storage_matrix_0_ROM_AUTO_1R #(
    .DataWidth( 1 ),
    .AddressRange( 16384 ),
    .AddressWidth( 14 ))
p_ZL14storage_matrix_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(p_ZL14storage_matrix_0_address0),
    .ce0(p_ZL14storage_matrix_0_ce0),
    .q0(p_ZL14storage_matrix_0_q0),
    .address1(p_ZL14storage_matrix_0_address1),
    .ce1(p_ZL14storage_matrix_0_ce1),
    .q1(p_ZL14storage_matrix_0_q1)
);

spiking_binam_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln52_fu_436_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            bank_fu_78 <= add_ln52_fu_442_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            bank_fu_78 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        bank_1_reg_625 <= ap_sig_allocacmp_bank_1;
        zext_ln52_reg_674[5 : 0] <= zext_ln52_fu_503_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_ZL14storage_matrix_1_load_reg_695 == 1'd1))) begin
        icmp_ln1019_1_reg_768 <= icmp_ln1019_1_fu_520_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_ZL14storage_matrix_2_load_reg_704 == 1'd1))) begin
        icmp_ln1019_2_reg_778 <= icmp_ln1019_2_fu_526_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_ZL14storage_matrix_3_load_reg_713 == 1'd1))) begin
        icmp_ln1019_3_reg_788 <= icmp_ln1019_3_fu_532_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_ZL14storage_matrix_0_load_1_reg_722 == 1'd1))) begin
        icmp_ln1019_4_reg_798 <= icmp_ln1019_4_fu_538_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_ZL14storage_matrix_1_load_1_reg_731 == 1'd1))) begin
        icmp_ln1019_5_reg_808 <= icmp_ln1019_5_fu_544_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_ZL14storage_matrix_2_load_1_reg_740 == 1'd1))) begin
        icmp_ln1019_6_reg_818 <= icmp_ln1019_6_fu_550_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_ZL14storage_matrix_3_load_1_reg_749 == 1'd1))) begin
        icmp_ln1019_7_reg_828 <= icmp_ln1019_7_fu_556_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_ZL14storage_matrix_0_load_reg_686 == 1'd1))) begin
        icmp_ln1019_reg_758 <= icmp_ln1019_fu_514_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL14storage_matrix_0_load_1_reg_722 <= p_ZL14storage_matrix_0_q0;
        p_ZL14storage_matrix_0_load_reg_686 <= p_ZL14storage_matrix_0_q1;
        p_ZL14storage_matrix_1_load_1_reg_731 <= p_ZL14storage_matrix_1_q0;
        p_ZL14storage_matrix_1_load_reg_695 <= p_ZL14storage_matrix_1_q1;
        p_ZL14storage_matrix_2_load_1_reg_740 <= p_ZL14storage_matrix_2_q0;
        p_ZL14storage_matrix_2_load_reg_704 <= p_ZL14storage_matrix_2_q1;
        p_ZL14storage_matrix_3_load_1_reg_749 <= p_ZL14storage_matrix_3_q0;
        p_ZL14storage_matrix_3_load_reg_713 <= p_ZL14storage_matrix_3_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        p_ZL14storage_matrix_0_load_1_reg_722_pp0_iter2_reg <= p_ZL14storage_matrix_0_load_1_reg_722;
        p_ZL14storage_matrix_0_load_reg_686_pp0_iter2_reg <= p_ZL14storage_matrix_0_load_reg_686;
        p_ZL14storage_matrix_1_load_1_reg_731_pp0_iter2_reg <= p_ZL14storage_matrix_1_load_1_reg_731;
        p_ZL14storage_matrix_1_load_reg_695_pp0_iter2_reg <= p_ZL14storage_matrix_1_load_reg_695;
        p_ZL14storage_matrix_2_load_1_reg_740_pp0_iter2_reg <= p_ZL14storage_matrix_2_load_1_reg_740;
        p_ZL14storage_matrix_2_load_reg_704_pp0_iter2_reg <= p_ZL14storage_matrix_2_load_reg_704;
        p_ZL14storage_matrix_3_load_1_reg_749_pp0_iter2_reg <= p_ZL14storage_matrix_3_load_1_reg_749;
        p_ZL14storage_matrix_3_load_reg_713_pp0_iter2_reg <= p_ZL14storage_matrix_3_load_reg_713;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1019_1_fu_520_p2 == 1'd1) & (p_ZL14storage_matrix_1_load_reg_695 == 1'd1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_addr_reg_772 <= zext_ln52_reg_674;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1019_2_fu_526_p2 == 1'd1) & (p_ZL14storage_matrix_2_load_reg_704 == 1'd1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_addr_reg_782 <= zext_ln52_reg_674;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1019_3_fu_532_p2 == 1'd1) & (p_ZL14storage_matrix_3_load_reg_713 == 1'd1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_addr_reg_792 <= zext_ln52_reg_674;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1019_4_fu_538_p2 == 1'd1) & (p_ZL14storage_matrix_0_load_1_reg_722 == 1'd1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_addr_reg_802 <= zext_ln52_reg_674;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1019_5_fu_544_p2 == 1'd1) & (p_ZL14storage_matrix_1_load_1_reg_731 == 1'd1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_addr_reg_812 <= zext_ln52_reg_674;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1019_6_fu_550_p2 == 1'd1) & (p_ZL14storage_matrix_2_load_1_reg_740 == 1'd1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_addr_reg_822 <= zext_ln52_reg_674;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1019_7_fu_556_p2 == 1'd1) & (p_ZL14storage_matrix_3_load_1_reg_749 == 1'd1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_addr_reg_832 <= zext_ln52_reg_674;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1019_fu_514_p2 == 1'd1) & (p_ZL14storage_matrix_0_load_reg_686 == 1'd1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_addr_reg_762 <= zext_ln52_reg_674;
    end
end

always @ (*) begin
    if (((icmp_ln52_fu_436_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_bank_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_bank_1 = bank_fu_78;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL14storage_matrix_0_ce0 = 1'b1;
    end else begin
        p_ZL14storage_matrix_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL14storage_matrix_0_ce1 = 1'b1;
    end else begin
        p_ZL14storage_matrix_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL14storage_matrix_1_ce0 = 1'b1;
    end else begin
        p_ZL14storage_matrix_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL14storage_matrix_1_ce1 = 1'b1;
    end else begin
        p_ZL14storage_matrix_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL14storage_matrix_2_ce0 = 1'b1;
    end else begin
        p_ZL14storage_matrix_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL14storage_matrix_2_ce1 = 1'b1;
    end else begin
        p_ZL14storage_matrix_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL14storage_matrix_3_ce0 = 1'b1;
    end else begin
        p_ZL14storage_matrix_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZL14storage_matrix_3_ce1 = 1'b1;
    end else begin
        p_ZL14storage_matrix_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce1 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1019_1_reg_768 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (p_ZL14storage_matrix_1_load_reg_695_pp0_iter2_reg == 1'd1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_we0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce1 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1019_2_reg_778 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (p_ZL14storage_matrix_2_load_reg_704_pp0_iter2_reg == 1'd1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_we0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce1 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1019_3_reg_788 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (p_ZL14storage_matrix_3_load_reg_713_pp0_iter2_reg == 1'd1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_we0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce1 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1019_4_reg_798 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (p_ZL14storage_matrix_0_load_1_reg_722_pp0_iter2_reg == 1'd1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_we0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce1 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1019_5_reg_808 == 1'd1) & (p_ZL14storage_matrix_1_load_1_reg_731_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_we0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce1 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1019_6_reg_818 == 1'd1) & (p_ZL14storage_matrix_2_load_1_reg_740_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_we0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce1 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1019_7_reg_828 == 1'd1) & (p_ZL14storage_matrix_3_load_1_reg_749_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_we0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce1 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1019_reg_758 == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1) & (p_ZL14storage_matrix_0_load_reg_686_pp0_iter2_reg == 1'd1))) begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_we0 = 1'b1;
    end else begin
        spiking_binam_stream_Spike_0_int_stream_Spike_0_v_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_fu_442_p2 = (ap_sig_allocacmp_bank_1 + 6'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln1019_1_fu_520_p2 = ((spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_q0 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1019_2_fu_526_p2 = ((spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_q0 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1019_3_fu_532_p2 = ((spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_q0 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1019_4_fu_538_p2 = ((spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_q0 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1019_5_fu_544_p2 = ((spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_q0 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1019_6_fu_550_p2 = ((spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_q0 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1019_7_fu_556_p2 = ((spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_q0 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln1019_fu_514_p2 = ((spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_q0 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_436_p2 = ((ap_sig_allocacmp_bank_1 == 6'd32) ? 1'b1 : 1'b0);

assign or_ln56_fu_476_p2 = (shl_ln56_fu_452_p2 | 6'd1);

assign p_ZL14storage_matrix_0_address0 = zext_ln56_1_fu_490_p1;

assign p_ZL14storage_matrix_0_address1 = zext_ln56_fu_468_p1;

assign p_ZL14storage_matrix_1_address0 = zext_ln56_1_fu_490_p1;

assign p_ZL14storage_matrix_1_address1 = zext_ln56_fu_468_p1;

assign p_ZL14storage_matrix_2_address0 = zext_ln56_1_fu_490_p1;

assign p_ZL14storage_matrix_2_address1 = zext_ln56_fu_468_p1;

assign p_ZL14storage_matrix_3_address0 = zext_ln56_1_fu_490_p1;

assign p_ZL14storage_matrix_3_address1 = zext_ln56_fu_468_p1;

assign shl_ln56_fu_452_p2 = ap_sig_allocacmp_bank_1 << 6'd1;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_address0 = zext_ln52_fu_503_p1;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_address0 = zext_ln52_fu_503_p1;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_address0 = zext_ln52_fu_503_p1;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_address0 = zext_ln52_fu_503_p1;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_address0 = zext_ln52_fu_503_p1;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_address0 = zext_ln52_fu_503_p1;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_address0 = zext_ln52_fu_503_p1;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_address0 = zext_ln52_fu_503_p1;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_address0 = spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_addr_reg_772;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_address1 = zext_ln52_reg_674;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_d0 = (spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_q1 + 7'd13);

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_address0 = spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_addr_reg_782;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_address1 = zext_ln52_reg_674;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_d0 = (spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_q1 + 7'd13);

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_address0 = spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_addr_reg_792;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_address1 = zext_ln52_reg_674;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_d0 = (spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_q1 + 7'd13);

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_address0 = spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_addr_reg_802;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_address1 = zext_ln52_reg_674;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_d0 = (spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_q1 + 7'd13);

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_address0 = spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_addr_reg_812;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_address1 = zext_ln52_reg_674;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_d0 = (spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_q1 + 7'd13);

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_address0 = spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_addr_reg_822;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_address1 = zext_ln52_reg_674;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_d0 = (spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_q1 + 7'd13);

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_address0 = spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_addr_reg_832;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_address1 = zext_ln52_reg_674;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_d0 = (spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_q1 + 7'd13);

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_address0 = spiking_binam_stream_Spike_0_int_stream_Spike_0_v_addr_reg_762;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_address1 = zext_ln52_reg_674;

assign spiking_binam_stream_Spike_0_int_stream_Spike_0_v_d0 = (spiking_binam_stream_Spike_0_int_stream_Spike_0_v_q1 + 7'd13);

assign tmp_4_fu_458_p4 = {{{cur_id_V_5}, {trunc_ln56_fu_448_p1}}, {1'd0}};

assign tmp_6_fu_482_p3 = {{cur_id_V_5}, {or_ln56_fu_476_p2}};

assign trunc_ln56_fu_448_p1 = ap_sig_allocacmp_bank_1[4:0];

assign zext_ln52_fu_503_p1 = bank_1_reg_625;

assign zext_ln56_1_fu_490_p1 = tmp_6_fu_482_p3;

assign zext_ln56_fu_468_p1 = tmp_4_fu_458_p4;

always @ (posedge ap_clk) begin
    zext_ln52_reg_674[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_52_4
