-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_52_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    cur_id_V_5 : IN STD_LOGIC_VECTOR (7 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_q0 : IN STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_q1 : IN STD_LOGIC_VECTOR (6 downto 0) );
end;


architecture behav of spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_52_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv7_D : STD_LOGIC_VECTOR (6 downto 0) := "0001101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln52_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal p_ZL14storage_matrix_3_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_ZL14storage_matrix_3_ce0 : STD_LOGIC;
    signal p_ZL14storage_matrix_3_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_3_address1 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_ZL14storage_matrix_3_ce1 : STD_LOGIC;
    signal p_ZL14storage_matrix_3_q1 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_2_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_ZL14storage_matrix_2_ce0 : STD_LOGIC;
    signal p_ZL14storage_matrix_2_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_2_address1 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_ZL14storage_matrix_2_ce1 : STD_LOGIC;
    signal p_ZL14storage_matrix_2_q1 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_1_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_ZL14storage_matrix_1_ce0 : STD_LOGIC;
    signal p_ZL14storage_matrix_1_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_1_address1 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_ZL14storage_matrix_1_ce1 : STD_LOGIC;
    signal p_ZL14storage_matrix_1_q1 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_0_address0 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_ZL14storage_matrix_0_ce0 : STD_LOGIC;
    signal p_ZL14storage_matrix_0_q0 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_0_address1 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_ZL14storage_matrix_0_ce1 : STD_LOGIC;
    signal p_ZL14storage_matrix_0_q1 : STD_LOGIC_VECTOR (0 downto 0);
    signal bank_1_reg_625 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln52_fu_503_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln52_reg_674 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_ZL14storage_matrix_0_load_reg_686 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_0_load_reg_686_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_1_load_reg_695 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_1_load_reg_695_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_2_load_reg_704 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_2_load_reg_704_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_3_load_reg_713 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_3_load_reg_713_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_0_load_1_reg_722 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_0_load_1_reg_722_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_1_load_1_reg_731 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_1_load_1_reg_731_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_2_load_1_reg_740 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_2_load_1_reg_740_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_3_load_1_reg_749 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_ZL14storage_matrix_3_load_1_reg_749_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_fu_514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_reg_758 : STD_LOGIC_VECTOR (0 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_v_addr_reg_762 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln1019_1_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_1_reg_768 : STD_LOGIC_VECTOR (0 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_addr_reg_772 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln1019_2_fu_526_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_2_reg_778 : STD_LOGIC_VECTOR (0 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_addr_reg_782 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln1019_3_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_3_reg_788 : STD_LOGIC_VECTOR (0 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_addr_reg_792 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln1019_4_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_4_reg_798 : STD_LOGIC_VECTOR (0 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_addr_reg_802 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln1019_5_fu_544_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_5_reg_808 : STD_LOGIC_VECTOR (0 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_addr_reg_812 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln1019_6_fu_550_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_6_reg_818 : STD_LOGIC_VECTOR (0 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_addr_reg_822 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln1019_7_fu_556_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1019_7_reg_828 : STD_LOGIC_VECTOR (0 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_addr_reg_832 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln56_fu_468_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln56_1_fu_490_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bank_fu_78 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln52_fu_442_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_bank_1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln56_fu_448_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_4_fu_458_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln56_fu_452_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal or_ln56_fu_476_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_6_fu_482_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_52_4_p_ZL14storage_matrix_3_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        address1 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_52_4_p_ZL14storage_matrix_2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        address1 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_52_4_p_ZL14storage_matrix_1_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        address1 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_52_4_p_ZL14storage_matrix_0_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (0 downto 0);
        address1 : IN STD_LOGIC_VECTOR (13 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component spiking_binam_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    p_ZL14storage_matrix_3_U : component spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_52_4_p_ZL14storage_matrix_3_ROM_AUTO_1R
    generic map (
        DataWidth => 1,
        AddressRange => 16384,
        AddressWidth => 14)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL14storage_matrix_3_address0,
        ce0 => p_ZL14storage_matrix_3_ce0,
        q0 => p_ZL14storage_matrix_3_q0,
        address1 => p_ZL14storage_matrix_3_address1,
        ce1 => p_ZL14storage_matrix_3_ce1,
        q1 => p_ZL14storage_matrix_3_q1);

    p_ZL14storage_matrix_2_U : component spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_52_4_p_ZL14storage_matrix_2_ROM_AUTO_1R
    generic map (
        DataWidth => 1,
        AddressRange => 16384,
        AddressWidth => 14)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL14storage_matrix_2_address0,
        ce0 => p_ZL14storage_matrix_2_ce0,
        q0 => p_ZL14storage_matrix_2_q0,
        address1 => p_ZL14storage_matrix_2_address1,
        ce1 => p_ZL14storage_matrix_2_ce1,
        q1 => p_ZL14storage_matrix_2_q1);

    p_ZL14storage_matrix_1_U : component spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_52_4_p_ZL14storage_matrix_1_ROM_AUTO_1R
    generic map (
        DataWidth => 1,
        AddressRange => 16384,
        AddressWidth => 14)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL14storage_matrix_1_address0,
        ce0 => p_ZL14storage_matrix_1_ce0,
        q0 => p_ZL14storage_matrix_1_q0,
        address1 => p_ZL14storage_matrix_1_address1,
        ce1 => p_ZL14storage_matrix_1_ce1,
        q1 => p_ZL14storage_matrix_1_q1);

    p_ZL14storage_matrix_0_U : component spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_52_4_p_ZL14storage_matrix_0_ROM_AUTO_1R
    generic map (
        DataWidth => 1,
        AddressRange => 16384,
        AddressWidth => 14)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL14storage_matrix_0_address0,
        ce0 => p_ZL14storage_matrix_0_ce0,
        q0 => p_ZL14storage_matrix_0_q0,
        address1 => p_ZL14storage_matrix_0_address1,
        ce1 => p_ZL14storage_matrix_0_ce1,
        q1 => p_ZL14storage_matrix_0_q1);

    flow_control_loop_pipe_sequential_init_U : component spiking_binam_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    bank_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln52_fu_436_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    bank_fu_78 <= add_ln52_fu_442_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    bank_fu_78 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                bank_1_reg_625 <= ap_sig_allocacmp_bank_1;
                    zext_ln52_reg_674(5 downto 0) <= zext_ln52_fu_503_p1(5 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (p_ZL14storage_matrix_1_load_reg_695 = ap_const_lv1_1))) then
                icmp_ln1019_1_reg_768 <= icmp_ln1019_1_fu_520_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (p_ZL14storage_matrix_2_load_reg_704 = ap_const_lv1_1))) then
                icmp_ln1019_2_reg_778 <= icmp_ln1019_2_fu_526_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (p_ZL14storage_matrix_3_load_reg_713 = ap_const_lv1_1))) then
                icmp_ln1019_3_reg_788 <= icmp_ln1019_3_fu_532_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (p_ZL14storage_matrix_0_load_1_reg_722 = ap_const_lv1_1))) then
                icmp_ln1019_4_reg_798 <= icmp_ln1019_4_fu_538_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (p_ZL14storage_matrix_1_load_1_reg_731 = ap_const_lv1_1))) then
                icmp_ln1019_5_reg_808 <= icmp_ln1019_5_fu_544_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (p_ZL14storage_matrix_2_load_1_reg_740 = ap_const_lv1_1))) then
                icmp_ln1019_6_reg_818 <= icmp_ln1019_6_fu_550_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (p_ZL14storage_matrix_3_load_1_reg_749 = ap_const_lv1_1))) then
                icmp_ln1019_7_reg_828 <= icmp_ln1019_7_fu_556_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (p_ZL14storage_matrix_0_load_reg_686 = ap_const_lv1_1))) then
                icmp_ln1019_reg_758 <= icmp_ln1019_fu_514_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                p_ZL14storage_matrix_0_load_1_reg_722 <= p_ZL14storage_matrix_0_q0;
                p_ZL14storage_matrix_0_load_reg_686 <= p_ZL14storage_matrix_0_q1;
                p_ZL14storage_matrix_1_load_1_reg_731 <= p_ZL14storage_matrix_1_q0;
                p_ZL14storage_matrix_1_load_reg_695 <= p_ZL14storage_matrix_1_q1;
                p_ZL14storage_matrix_2_load_1_reg_740 <= p_ZL14storage_matrix_2_q0;
                p_ZL14storage_matrix_2_load_reg_704 <= p_ZL14storage_matrix_2_q1;
                p_ZL14storage_matrix_3_load_1_reg_749 <= p_ZL14storage_matrix_3_q0;
                p_ZL14storage_matrix_3_load_reg_713 <= p_ZL14storage_matrix_3_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                p_ZL14storage_matrix_0_load_1_reg_722_pp0_iter2_reg <= p_ZL14storage_matrix_0_load_1_reg_722;
                p_ZL14storage_matrix_0_load_reg_686_pp0_iter2_reg <= p_ZL14storage_matrix_0_load_reg_686;
                p_ZL14storage_matrix_1_load_1_reg_731_pp0_iter2_reg <= p_ZL14storage_matrix_1_load_1_reg_731;
                p_ZL14storage_matrix_1_load_reg_695_pp0_iter2_reg <= p_ZL14storage_matrix_1_load_reg_695;
                p_ZL14storage_matrix_2_load_1_reg_740_pp0_iter2_reg <= p_ZL14storage_matrix_2_load_1_reg_740;
                p_ZL14storage_matrix_2_load_reg_704_pp0_iter2_reg <= p_ZL14storage_matrix_2_load_reg_704;
                p_ZL14storage_matrix_3_load_1_reg_749_pp0_iter2_reg <= p_ZL14storage_matrix_3_load_1_reg_749;
                p_ZL14storage_matrix_3_load_reg_713_pp0_iter2_reg <= p_ZL14storage_matrix_3_load_reg_713;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1019_1_fu_520_p2 = ap_const_lv1_1) and (p_ZL14storage_matrix_1_load_reg_695 = ap_const_lv1_1))) then
                spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_addr_reg_772 <= zext_ln52_reg_674(5 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1019_2_fu_526_p2 = ap_const_lv1_1) and (p_ZL14storage_matrix_2_load_reg_704 = ap_const_lv1_1))) then
                spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_addr_reg_782 <= zext_ln52_reg_674(5 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1019_3_fu_532_p2 = ap_const_lv1_1) and (p_ZL14storage_matrix_3_load_reg_713 = ap_const_lv1_1))) then
                spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_addr_reg_792 <= zext_ln52_reg_674(5 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1019_4_fu_538_p2 = ap_const_lv1_1) and (p_ZL14storage_matrix_0_load_1_reg_722 = ap_const_lv1_1))) then
                spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_addr_reg_802 <= zext_ln52_reg_674(5 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1019_5_fu_544_p2 = ap_const_lv1_1) and (p_ZL14storage_matrix_1_load_1_reg_731 = ap_const_lv1_1))) then
                spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_addr_reg_812 <= zext_ln52_reg_674(5 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1019_6_fu_550_p2 = ap_const_lv1_1) and (p_ZL14storage_matrix_2_load_1_reg_740 = ap_const_lv1_1))) then
                spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_addr_reg_822 <= zext_ln52_reg_674(5 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1019_7_fu_556_p2 = ap_const_lv1_1) and (p_ZL14storage_matrix_3_load_1_reg_749 = ap_const_lv1_1))) then
                spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_addr_reg_832 <= zext_ln52_reg_674(5 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1019_fu_514_p2 = ap_const_lv1_1) and (p_ZL14storage_matrix_0_load_reg_686 = ap_const_lv1_1))) then
                spiking_binam_stream_Spike_0_int_stream_Spike_0_v_addr_reg_762 <= zext_ln52_reg_674(5 - 1 downto 0);
            end if;
        end if;
    end process;
    zext_ln52_reg_674(63 downto 6) <= "0000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln52_fu_442_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_bank_1) + unsigned(ap_const_lv6_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln52_fu_436_p2)
    begin
        if (((icmp_ln52_fu_436_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_bank_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, bank_fu_78, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_bank_1 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_bank_1 <= bank_fu_78;
        end if; 
    end process;

    icmp_ln1019_1_fu_520_p2 <= "1" when (spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_q0 = ap_const_lv3_0) else "0";
    icmp_ln1019_2_fu_526_p2 <= "1" when (spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_q0 = ap_const_lv3_0) else "0";
    icmp_ln1019_3_fu_532_p2 <= "1" when (spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_q0 = ap_const_lv3_0) else "0";
    icmp_ln1019_4_fu_538_p2 <= "1" when (spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_q0 = ap_const_lv3_0) else "0";
    icmp_ln1019_5_fu_544_p2 <= "1" when (spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_q0 = ap_const_lv3_0) else "0";
    icmp_ln1019_6_fu_550_p2 <= "1" when (spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_q0 = ap_const_lv3_0) else "0";
    icmp_ln1019_7_fu_556_p2 <= "1" when (spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_q0 = ap_const_lv3_0) else "0";
    icmp_ln1019_fu_514_p2 <= "1" when (spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_q0 = ap_const_lv3_0) else "0";
    icmp_ln52_fu_436_p2 <= "1" when (ap_sig_allocacmp_bank_1 = ap_const_lv6_20) else "0";
    or_ln56_fu_476_p2 <= (shl_ln56_fu_452_p2 or ap_const_lv6_1);
    p_ZL14storage_matrix_0_address0 <= zext_ln56_1_fu_490_p1(14 - 1 downto 0);
    p_ZL14storage_matrix_0_address1 <= zext_ln56_fu_468_p1(14 - 1 downto 0);

    p_ZL14storage_matrix_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL14storage_matrix_0_ce0 <= ap_const_logic_1;
        else 
            p_ZL14storage_matrix_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZL14storage_matrix_0_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL14storage_matrix_0_ce1 <= ap_const_logic_1;
        else 
            p_ZL14storage_matrix_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL14storage_matrix_1_address0 <= zext_ln56_1_fu_490_p1(14 - 1 downto 0);
    p_ZL14storage_matrix_1_address1 <= zext_ln56_fu_468_p1(14 - 1 downto 0);

    p_ZL14storage_matrix_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL14storage_matrix_1_ce0 <= ap_const_logic_1;
        else 
            p_ZL14storage_matrix_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZL14storage_matrix_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL14storage_matrix_1_ce1 <= ap_const_logic_1;
        else 
            p_ZL14storage_matrix_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL14storage_matrix_2_address0 <= zext_ln56_1_fu_490_p1(14 - 1 downto 0);
    p_ZL14storage_matrix_2_address1 <= zext_ln56_fu_468_p1(14 - 1 downto 0);

    p_ZL14storage_matrix_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL14storage_matrix_2_ce0 <= ap_const_logic_1;
        else 
            p_ZL14storage_matrix_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZL14storage_matrix_2_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL14storage_matrix_2_ce1 <= ap_const_logic_1;
        else 
            p_ZL14storage_matrix_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL14storage_matrix_3_address0 <= zext_ln56_1_fu_490_p1(14 - 1 downto 0);
    p_ZL14storage_matrix_3_address1 <= zext_ln56_fu_468_p1(14 - 1 downto 0);

    p_ZL14storage_matrix_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL14storage_matrix_3_ce0 <= ap_const_logic_1;
        else 
            p_ZL14storage_matrix_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    p_ZL14storage_matrix_3_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL14storage_matrix_3_ce1 <= ap_const_logic_1;
        else 
            p_ZL14storage_matrix_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    shl_ln56_fu_452_p2 <= std_logic_vector(shift_left(unsigned(ap_sig_allocacmp_bank_1),to_integer(unsigned('0' & ap_const_lv6_1(6-1 downto 0)))));
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_address0 <= zext_ln52_fu_503_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_address0 <= zext_ln52_fu_503_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_address0 <= zext_ln52_fu_503_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_address0 <= zext_ln52_fu_503_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_address0 <= zext_ln52_fu_503_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_address0 <= zext_ln52_fu_503_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_address0 <= zext_ln52_fu_503_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_address0 <= zext_ln52_fu_503_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_addr_reg_772;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_address1 <= zext_ln52_reg_674(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_d0 <= std_logic_vector(unsigned(spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_q1) + unsigned(ap_const_lv7_D));

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_we0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, p_ZL14storage_matrix_1_load_reg_695_pp0_iter2_reg, icmp_ln1019_1_reg_768)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1019_1_reg_768 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (p_ZL14storage_matrix_1_load_reg_695_pp0_iter2_reg = ap_const_lv1_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_addr_reg_782;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_address1 <= zext_ln52_reg_674(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_d0 <= std_logic_vector(unsigned(spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_q1) + unsigned(ap_const_lv7_D));

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_we0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, p_ZL14storage_matrix_2_load_reg_704_pp0_iter2_reg, icmp_ln1019_2_reg_778)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1019_2_reg_778 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (p_ZL14storage_matrix_2_load_reg_704_pp0_iter2_reg = ap_const_lv1_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_addr_reg_792;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_address1 <= zext_ln52_reg_674(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_d0 <= std_logic_vector(unsigned(spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_q1) + unsigned(ap_const_lv7_D));

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_we0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, p_ZL14storage_matrix_3_load_reg_713_pp0_iter2_reg, icmp_ln1019_3_reg_788)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1019_3_reg_788 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (p_ZL14storage_matrix_3_load_reg_713_pp0_iter2_reg = ap_const_lv1_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_addr_reg_802;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_address1 <= zext_ln52_reg_674(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_d0 <= std_logic_vector(unsigned(spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_q1) + unsigned(ap_const_lv7_D));

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_we0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, p_ZL14storage_matrix_0_load_1_reg_722_pp0_iter2_reg, icmp_ln1019_4_reg_798)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1019_4_reg_798 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (p_ZL14storage_matrix_0_load_1_reg_722_pp0_iter2_reg = ap_const_lv1_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_addr_reg_812;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_address1 <= zext_ln52_reg_674(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_d0 <= std_logic_vector(unsigned(spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_q1) + unsigned(ap_const_lv7_D));

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_we0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, p_ZL14storage_matrix_1_load_1_reg_731_pp0_iter2_reg, icmp_ln1019_5_reg_808)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1019_5_reg_808 = ap_const_lv1_1) and (p_ZL14storage_matrix_1_load_1_reg_731_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_addr_reg_822;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_address1 <= zext_ln52_reg_674(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_d0 <= std_logic_vector(unsigned(spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_q1) + unsigned(ap_const_lv7_D));

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_we0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, p_ZL14storage_matrix_2_load_1_reg_740_pp0_iter2_reg, icmp_ln1019_6_reg_818)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1019_6_reg_818 = ap_const_lv1_1) and (p_ZL14storage_matrix_2_load_1_reg_740_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_addr_reg_832;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_address1 <= zext_ln52_reg_674(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_d0 <= std_logic_vector(unsigned(spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_q1) + unsigned(ap_const_lv7_D));

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_we0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, p_ZL14storage_matrix_3_load_1_reg_749_pp0_iter2_reg, icmp_ln1019_7_reg_828)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1019_7_reg_828 = ap_const_lv1_1) and (p_ZL14storage_matrix_3_load_1_reg_749_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_v_addr_reg_762;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_address1 <= zext_ln52_reg_674(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_d0 <= std_logic_vector(unsigned(spiking_binam_stream_Spike_0_int_stream_Spike_0_v_q1) + unsigned(ap_const_lv7_D));

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_we0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001, p_ZL14storage_matrix_0_load_reg_686_pp0_iter2_reg, icmp_ln1019_reg_758)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1019_reg_758 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (p_ZL14storage_matrix_0_load_reg_686_pp0_iter2_reg = ap_const_lv1_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_4_fu_458_p4 <= ((cur_id_V_5 & trunc_ln56_fu_448_p1) & ap_const_lv1_0);
    tmp_6_fu_482_p3 <= (cur_id_V_5 & or_ln56_fu_476_p2);
    trunc_ln56_fu_448_p1 <= ap_sig_allocacmp_bank_1(5 - 1 downto 0);
    zext_ln52_fu_503_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(bank_1_reg_625),64));
    zext_ln56_1_fu_490_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_482_p3),64));
    zext_ln56_fu_468_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_458_p4),64));
end behav;
