-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_67_6 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_q1 : IN STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_q1 : IN STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_q1 : IN STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_q1 : IN STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_q1 : IN STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_q1 : IN STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_q1 : IN STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_q1 : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_67_6 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln67_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_addr_reg_306 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_addr_reg_312 : STD_LOGIC_VECTOR (4 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_addr_reg_318 : STD_LOGIC_VECTOR (4 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_addr_reg_324 : STD_LOGIC_VECTOR (4 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_addr_reg_330 : STD_LOGIC_VECTOR (4 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_addr_reg_336 : STD_LOGIC_VECTOR (4 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_addr_reg_342 : STD_LOGIC_VECTOR (4 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_addr_reg_348 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln1035_fu_246_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln1035_reg_354 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln1035_fu_234_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal i_1_fu_64 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln67_fu_218_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln1035_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln841_fu_282_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal lshr_ln1_fu_224_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_2_fu_255_p10 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component spiking_binam_mux_83_3_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (2 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        din2 : IN STD_LOGIC_VECTOR (2 downto 0);
        din3 : IN STD_LOGIC_VECTOR (2 downto 0);
        din4 : IN STD_LOGIC_VECTOR (2 downto 0);
        din5 : IN STD_LOGIC_VECTOR (2 downto 0);
        din6 : IN STD_LOGIC_VECTOR (2 downto 0);
        din7 : IN STD_LOGIC_VECTOR (2 downto 0);
        din8 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component spiking_binam_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_83_3_1_1_U38 : component spiking_binam_mux_83_3_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 3,
        din1_WIDTH => 3,
        din2_WIDTH => 3,
        din3_WIDTH => 3,
        din4_WIDTH => 3,
        din5_WIDTH => 3,
        din6_WIDTH => 3,
        din7_WIDTH => 3,
        din8_WIDTH => 3,
        dout_WIDTH => 3)
    port map (
        din0 => spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_q1,
        din1 => spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_q1,
        din2 => spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_q1,
        din3 => spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_q1,
        din4 => spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_q1,
        din5 => spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_q1,
        din6 => spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_q1,
        din7 => spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_q1,
        din8 => trunc_ln1035_reg_354,
        dout => tmp_2_fu_255_p10);

    flow_control_loop_pipe_sequential_init_U : component spiking_binam_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_1_fu_64_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln67_fu_212_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_1_fu_64 <= add_ln67_fu_218_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_1_fu_64 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln67_fu_212_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_addr_reg_324 <= zext_ln1035_fu_234_p1(5 - 1 downto 0);
                spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_addr_reg_330 <= zext_ln1035_fu_234_p1(5 - 1 downto 0);
                spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_addr_reg_336 <= zext_ln1035_fu_234_p1(5 - 1 downto 0);
                spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_addr_reg_342 <= zext_ln1035_fu_234_p1(5 - 1 downto 0);
                spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_addr_reg_348 <= zext_ln1035_fu_234_p1(5 - 1 downto 0);
                spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_addr_reg_312 <= zext_ln1035_fu_234_p1(5 - 1 downto 0);
                spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_addr_reg_318 <= zext_ln1035_fu_234_p1(5 - 1 downto 0);
                spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_addr_reg_306 <= zext_ln1035_fu_234_p1(5 - 1 downto 0);
                trunc_ln1035_reg_354 <= trunc_ln1035_fu_246_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln67_fu_218_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv9_1));
    add_ln841_fu_282_p2 <= std_logic_vector(unsigned(tmp_2_fu_255_p10) + unsigned(ap_const_lv3_7));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln67_fu_212_p2)
    begin
        if (((icmp_ln67_fu_212_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_1_fu_64, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_i <= i_1_fu_64;
        end if; 
    end process;

    icmp_ln1035_fu_276_p2 <= "1" when (tmp_2_fu_255_p10 = ap_const_lv3_0) else "0";
    icmp_ln67_fu_212_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv9_100) else "0";
    lshr_ln1_fu_224_p4 <= ap_sig_allocacmp_i(7 downto 3);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_addr_reg_324;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_address1 <= zext_ln1035_fu_234_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_d0 <= add_ln841_fu_282_p2;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln1035_reg_354, icmp_ln1035_fu_276_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1035_fu_276_p2 = ap_const_lv1_0) and (trunc_ln1035_reg_354 = ap_const_lv3_3))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_addr_reg_330;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_address1 <= zext_ln1035_fu_234_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_d0 <= add_ln841_fu_282_p2;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln1035_reg_354, icmp_ln1035_fu_276_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1035_fu_276_p2 = ap_const_lv1_0) and (trunc_ln1035_reg_354 = ap_const_lv3_4))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_addr_reg_336;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_address1 <= zext_ln1035_fu_234_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_d0 <= add_ln841_fu_282_p2;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln1035_reg_354, icmp_ln1035_fu_276_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1035_fu_276_p2 = ap_const_lv1_0) and (trunc_ln1035_reg_354 = ap_const_lv3_5))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_addr_reg_342;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_address1 <= zext_ln1035_fu_234_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_d0 <= add_ln841_fu_282_p2;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln1035_reg_354, icmp_ln1035_fu_276_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1035_fu_276_p2 = ap_const_lv1_0) and (trunc_ln1035_reg_354 = ap_const_lv3_6))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_addr_reg_348;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_address1 <= zext_ln1035_fu_234_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_d0 <= add_ln841_fu_282_p2;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln1035_reg_354, icmp_ln1035_fu_276_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1035_fu_276_p2 = ap_const_lv1_0) and (trunc_ln1035_reg_354 = ap_const_lv3_7))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_addr_reg_312;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_address1 <= zext_ln1035_fu_234_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_d0 <= add_ln841_fu_282_p2;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln1035_reg_354, icmp_ln1035_fu_276_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1035_fu_276_p2 = ap_const_lv1_0) and (trunc_ln1035_reg_354 = ap_const_lv3_1))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_addr_reg_318;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_address1 <= zext_ln1035_fu_234_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_d0 <= add_ln841_fu_282_p2;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln1035_reg_354, icmp_ln1035_fu_276_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1035_fu_276_p2 = ap_const_lv1_0) and (trunc_ln1035_reg_354 = ap_const_lv3_2))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_addr_reg_306;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_address1 <= zext_ln1035_fu_234_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_d0 <= add_ln841_fu_282_p2;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln1035_reg_354, icmp_ln1035_fu_276_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1035_fu_276_p2 = ap_const_lv1_0) and (trunc_ln1035_reg_354 = ap_const_lv3_0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_we0 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln1035_fu_246_p1 <= ap_sig_allocacmp_i(3 - 1 downto 0);
    zext_ln1035_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln1_fu_224_p4),64));
end behav;
