-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_76_7 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_spikes_TREADY : IN STD_LOGIC;
    threshW : IN STD_LOGIC_VECTOR (6 downto 0);
    bin_start_V : IN STD_LOGIC_VECTOR (11 downto 0);
    out_spikes_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_spikes_TVALID : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_d0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce1 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_q1 : IN STD_LOGIC_VECTOR (6 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_d0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_we0 : OUT STD_LOGIC;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_d0 : OUT STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of spiking_binam_spiking_binam_Pipeline_VITIS_LOOP_76_7 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal icmp_ln1031_reg_571 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln76_fu_391_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal out_spikes_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_reg_493 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln1031_fu_413_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1031_reg_503 : STD_LOGIC_VECTOR (63 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_v_addr_reg_515 : STD_LOGIC_VECTOR (4 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_addr_reg_521 : STD_LOGIC_VECTOR (4 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_addr_reg_527 : STD_LOGIC_VECTOR (4 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_addr_reg_533 : STD_LOGIC_VECTOR (4 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_addr_reg_539 : STD_LOGIC_VECTOR (4 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_addr_reg_545 : STD_LOGIC_VECTOR (4 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_addr_reg_551 : STD_LOGIC_VECTOR (4 downto 0);
    signal spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_addr_reg_557 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln76_fu_430_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln76_reg_563 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1031_fu_458_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1031_fu_433_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal i_2_fu_104 : STD_LOGIC_VECTOR (8 downto 0);
    signal i_1_fu_397_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal lshr_ln2_fu_403_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_fu_436_p9 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_5_fu_436_p10 : STD_LOGIC_VECTOR (6 downto 0);
    signal or_ln_fu_463_p4 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component spiking_binam_mux_83_7_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (6 downto 0);
        din3 : IN STD_LOGIC_VECTOR (6 downto 0);
        din4 : IN STD_LOGIC_VECTOR (6 downto 0);
        din5 : IN STD_LOGIC_VECTOR (6 downto 0);
        din6 : IN STD_LOGIC_VECTOR (6 downto 0);
        din7 : IN STD_LOGIC_VECTOR (6 downto 0);
        din8 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;


    component spiking_binam_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_83_7_1_1_U48 : component spiking_binam_mux_83_7_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 7,
        din1_WIDTH => 7,
        din2_WIDTH => 7,
        din3_WIDTH => 7,
        din4_WIDTH => 7,
        din5_WIDTH => 7,
        din6_WIDTH => 7,
        din7_WIDTH => 7,
        din8_WIDTH => 3,
        dout_WIDTH => 7)
    port map (
        din0 => spiking_binam_stream_Spike_0_int_stream_Spike_0_v_q1,
        din1 => spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_q1,
        din2 => spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_q1,
        din3 => spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_q1,
        din4 => spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_q1,
        din5 => spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_q1,
        din6 => spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_q1,
        din7 => spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_q1,
        din8 => tmp_5_fu_436_p9,
        dout => tmp_5_fu_436_p10);

    flow_control_loop_pipe_sequential_init_U : component spiking_binam_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    i_2_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln76_fu_391_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_2_fu_104 <= i_1_fu_397_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_2_fu_104 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                i_reg_493 <= ap_sig_allocacmp_i;
                icmp_ln1031_reg_571 <= icmp_ln1031_fu_458_p2;
                trunc_ln76_reg_563 <= trunc_ln76_fu_430_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln76_fu_391_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_addr_reg_521 <= zext_ln1031_fu_413_p1(5 - 1 downto 0);
                spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_addr_reg_527 <= zext_ln1031_fu_413_p1(5 - 1 downto 0);
                spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_addr_reg_533 <= zext_ln1031_fu_413_p1(5 - 1 downto 0);
                spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_addr_reg_539 <= zext_ln1031_fu_413_p1(5 - 1 downto 0);
                spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_addr_reg_545 <= zext_ln1031_fu_413_p1(5 - 1 downto 0);
                spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_addr_reg_551 <= zext_ln1031_fu_413_p1(5 - 1 downto 0);
                spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_addr_reg_557 <= zext_ln1031_fu_413_p1(5 - 1 downto 0);
                spiking_binam_stream_Spike_0_int_stream_Spike_0_v_addr_reg_515 <= zext_ln1031_fu_413_p1(5 - 1 downto 0);
                    zext_ln1031_reg_503(4 downto 0) <= zext_ln1031_fu_413_p1(4 downto 0);
            end if;
        end if;
    end process;
    zext_ln1031_reg_503(63 downto 5) <= "00000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter2, out_spikes_TREADY, icmp_ln1031_reg_571)
    begin
                ap_block_pp0_stage0_01001 <= ((icmp_ln1031_reg_571 = ap_const_lv1_0) and (out_spikes_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter2, out_spikes_TREADY, icmp_ln1031_reg_571, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln1031_reg_571 = ap_const_lv1_0) and (out_spikes_TREADY = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter2, out_spikes_TREADY, icmp_ln1031_reg_571, ap_block_state3_io)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and ((ap_const_boolean_1 = ap_block_state3_io) or ((icmp_ln1031_reg_571 = ap_const_lv1_0) and (out_spikes_TREADY = ap_const_logic_0))));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_io_assign_proc : process(out_spikes_TREADY, icmp_ln1031_reg_571)
    begin
                ap_block_state3_io <= ((icmp_ln1031_reg_571 = ap_const_lv1_0) and (out_spikes_TREADY = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(out_spikes_TREADY, icmp_ln1031_reg_571)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((icmp_ln1031_reg_571 = ap_const_lv1_0) and (out_spikes_TREADY = ap_const_logic_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln76_fu_391_p2)
    begin
        if (((icmp_ln76_fu_391_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_2_fu_104, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_i <= i_2_fu_104;
        end if; 
    end process;

    i_1_fu_397_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i) + unsigned(ap_const_lv9_1));
    icmp_ln1031_fu_458_p2 <= "1" when (unsigned(threshW) > unsigned(tmp_5_fu_436_p10)) else "0";
    icmp_ln76_fu_391_p2 <= "1" when (ap_sig_allocacmp_i = ap_const_lv9_100) else "0";
    lshr_ln2_fu_403_p4 <= ap_sig_allocacmp_i(7 downto 3);
    or_ln_fu_463_p4 <= ((bin_start_V & ap_const_lv8_0) & trunc_ln76_reg_563);
    out_spikes_TDATA <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_463_p4),32));

    out_spikes_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, out_spikes_TREADY, icmp_ln1031_reg_571, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln1031_reg_571 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            out_spikes_TDATA_blk_n <= out_spikes_TREADY;
        else 
            out_spikes_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out_spikes_TVALID_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln1031_reg_571, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1031_reg_571 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            out_spikes_TVALID <= ap_const_logic_1;
        else 
            out_spikes_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_address0 <= zext_ln1031_reg_503(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_d0 <= ap_const_lv3_5;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln1031_fu_458_p2, trunc_ln1031_fu_433_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln1031_fu_433_p1 = ap_const_lv3_3) and (icmp_ln1031_fu_458_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_address0 <= zext_ln1031_reg_503(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_d0 <= ap_const_lv3_5;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln1031_fu_458_p2, trunc_ln1031_fu_433_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln1031_fu_433_p1 = ap_const_lv3_4) and (icmp_ln1031_fu_458_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_address0 <= zext_ln1031_reg_503(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_d0 <= ap_const_lv3_5;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln1031_fu_458_p2, trunc_ln1031_fu_433_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln1031_fu_433_p1 = ap_const_lv3_5) and (icmp_ln1031_fu_458_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_address0 <= zext_ln1031_reg_503(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_d0 <= ap_const_lv3_5;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln1031_fu_458_p2, trunc_ln1031_fu_433_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln1031_fu_433_p1 = ap_const_lv3_6) and (icmp_ln1031_fu_458_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_address0 <= zext_ln1031_reg_503(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_d0 <= ap_const_lv3_5;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln1031_fu_458_p2, trunc_ln1031_fu_433_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln1031_fu_433_p1 = ap_const_lv3_7) and (icmp_ln1031_fu_458_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_address0 <= zext_ln1031_reg_503(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_d0 <= ap_const_lv3_5;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln1031_fu_458_p2, trunc_ln1031_fu_433_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln1031_fu_433_p1 = ap_const_lv3_1) and (icmp_ln1031_fu_458_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_address0 <= zext_ln1031_reg_503(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_d0 <= ap_const_lv3_5;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln1031_fu_458_p2, trunc_ln1031_fu_433_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln1031_fu_433_p1 = ap_const_lv3_2) and (icmp_ln1031_fu_458_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_address0 <= zext_ln1031_reg_503(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_d0 <= ap_const_lv3_5;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln1031_fu_458_p2, trunc_ln1031_fu_433_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln1031_fu_433_p1 = ap_const_lv3_0) and (icmp_ln1031_fu_458_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_ref_timer_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_addr_reg_521;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_address1 <= zext_ln1031_fu_413_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_d0 <= ap_const_lv7_0;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln1031_fu_458_p2, trunc_ln1031_fu_433_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln1031_fu_433_p1 = ap_const_lv3_1) and (icmp_ln1031_fu_458_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_addr_reg_527;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_address1 <= zext_ln1031_fu_413_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_d0 <= ap_const_lv7_0;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln1031_fu_458_p2, trunc_ln1031_fu_433_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln1031_fu_433_p1 = ap_const_lv3_2) and (icmp_ln1031_fu_458_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_addr_reg_533;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_address1 <= zext_ln1031_fu_413_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_d0 <= ap_const_lv7_0;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln1031_fu_458_p2, trunc_ln1031_fu_433_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln1031_fu_433_p1 = ap_const_lv3_3) and (icmp_ln1031_fu_458_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_addr_reg_539;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_address1 <= zext_ln1031_fu_413_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_d0 <= ap_const_lv7_0;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln1031_fu_458_p2, trunc_ln1031_fu_433_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln1031_fu_433_p1 = ap_const_lv3_4) and (icmp_ln1031_fu_458_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_addr_reg_545;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_address1 <= zext_ln1031_fu_413_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_d0 <= ap_const_lv7_0;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln1031_fu_458_p2, trunc_ln1031_fu_433_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln1031_fu_433_p1 = ap_const_lv3_5) and (icmp_ln1031_fu_458_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_addr_reg_551;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_address1 <= zext_ln1031_fu_413_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_d0 <= ap_const_lv7_0;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln1031_fu_458_p2, trunc_ln1031_fu_433_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln1031_fu_433_p1 = ap_const_lv3_6) and (icmp_ln1031_fu_458_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_addr_reg_557;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_address1 <= zext_ln1031_fu_413_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_d0 <= ap_const_lv7_0;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln1031_fu_458_p2, trunc_ln1031_fu_433_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln1031_fu_433_p1 = ap_const_lv3_7) and (icmp_ln1031_fu_458_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_address0 <= spiking_binam_stream_Spike_0_int_stream_Spike_0_v_addr_reg_515;
    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_address1 <= zext_ln1031_fu_413_p1(5 - 1 downto 0);

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce1 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_d0 <= ap_const_lv7_0;

    spiking_binam_stream_Spike_0_int_stream_Spike_0_v_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln1031_fu_458_p2, trunc_ln1031_fu_433_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln1031_fu_433_p1 = ap_const_lv3_0) and (icmp_ln1031_fu_458_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_we0 <= ap_const_logic_1;
        else 
            spiking_binam_stream_Spike_0_int_stream_Spike_0_v_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_5_fu_436_p9 <= i_reg_493(3 - 1 downto 0);
    trunc_ln1031_fu_433_p1 <= i_reg_493(3 - 1 downto 0);
    trunc_ln76_fu_430_p1 <= i_reg_493(8 - 1 downto 0);
    zext_ln1031_fu_413_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln2_fu_403_p4),64));
end behav;
